### ISSUE TITLE
Add example project to test package configuration

### ISSUE THREAD

**Issue by schuhschuh** [gflags/gflags#106]
Use CMake's ExternalProject module to test the use of the build tree and installation, respectively, of the configured and build gflags library. This tests the export/import of the build targets and generated gflags package configuration (```gflags-config.cmake```). The test will ensure that the include directories and library dependencies used by external projects are correctly set.

Actually, the ExternalProject module may not be needed. A Python script which is run as test command which configures an example project that uses gflags should be sufficient.

**Comment by carlesfernandez** [comment]
Hi there,

at https://github.com/gnss-sdr/gnss-sdr/blob/next/CMakeLists.txt#L433 we use ExternalProject_Add to download, build and link to gflags. Works fine :-)

**Comment by schuhschuh** [comment]
Hey @carlesfernandez, cool! Thanks for the quick feedback :) I'd just like to have a test included so I notice immediately when I break the configuration before a release.
