### ISSUE TITLE
Problem Linker os-x and DECLARE

### ISSUE THREAD

**Issue by sducomman** [gflags/gflags#111]
Hello,
I use gflags via ortools, but recently I have made an update of ortools and I have problem of linker with the library gflags. 
The version used of gflags is 2.1.1 and I have tested on windows and mac.
On mac, with the example :

```
#include <gflags/gflags.h>
DECLARE_int64(myInt);
DEFINE_int64(deu, 64, "test");
int main(int argc, char ** argv) {
    gflags::ParseCommandLineFlags( &argc, &argv, true);
    std::cout << FLAGS_myInt << std::endl;
    std::cout << FLAGS_deu << std::endl;
    return 0;
}
```

I have the following error : 
Undefined symbols for architecture x86_64:
  "fLI64::FLAGS_myInt", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Sorry for the inconvenience, especially as I didn't know gflags without ortools.

Thank you in advance,

--
Sylvain Ducomman

**Comment by schuhschuh** [comment]
Hi Sylvain,

the linker correctly indicates the problem. You have only declared the global FLAGS_myint variable via DECLARE_int64, but not defined it in this compilation unit (.cc/.cxx/.cpp file). The DECLARE_int64 macro should enable you to use a flag in a compilation unit which is defined in another compilation unit or library. If you replace DECLARE_int64 by DEFINE_int64 the linker error should go away for this example.

If you encounter such linker error with a more complicated actual application set up, you need to check whether and where (i.e., in which .cc file or library) the flag is DEFINE'd. Then you must ensure that the respective object file or library is part of the linker command.

Best,
Andreas
