### ISSUE TITLE
.gitmodules is using SSH protocol instead of HTTPS

### ISSUE THREAD

**Issue by soonhokong** [gflags/gflags#112]
We have a machine where SSH key is not yet configured. On that machine, we have the following error:

```bash
$ git submodule update --recursive
Cloning into 'doc'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:gflags/gflags.git' into submodule path 'doc' failed
```

At line 3 of `.gitmodule` file, we have

```
         url = git@github.com:gflags/gflags.git
```

after changing the line to the following one, it works.

```
         url = https://github.com/gflags/gflags.git
```

**Comment by schuhschuh** [comment]
Thanks, I've made the suggested change.

**Comment by soonhokong** [comment]
:+1:

**Comment by ravneetarora** [comment]
but how can we have .gitmodules with https:// only? it is automatically checkout while fetching a repository

**Comment by schuhschuh** [comment]
The current .gitmodules does use the HTTPS protocol. Further, you can modify the file after cloning before initializing the submodule. If it's some automated build, you don't need to clone / update the submodule as it contains only the online documentation.

**Comment by ravneetarora** [comment]
hi,
mine is the automated build through bamboo. I am including checkout repository task which does not pull submodules on its own. it gives the error as 

Cloning into 'OAuthConsumer'...
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=Connection refused

Clone of 'git://github.com/aaaaaaaaaa/oauthconsumer' into submodule path 'OAuthConsumer' failed
No matching processes belonging to you were found
** BUILD FAILED **

**Comment by ravneetarora** [comment]
i found the answer. To resolve OAuthConsumer cloning errors, we have to give the below commands while pulling submodules

git submodule sync
git submodule update --init --recursive
