### ISSUE TITLE
cmake fails when BUILD_SHARED_LIBS and BUILD_STATIC_LIBS are ON

### ISSUE THREAD

**Issue by soonhokong** [gflags/gflags#113]
Repo steps:

```bash
mkdir build && cd build
cmake -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON ../
```

What I got:
```
CMake Error in CMakeLists.txt:
  Target "gflags-static" INTERFACE_INCLUDE_DIRECTORIES property contains
  relative path:

    "include"


CMake Error in CMakeLists.txt:
  Target "gflags_nothreads-static" INTERFACE_INCLUDE_DIRECTORIES property
  contains relative path:

    "include"


CMake Error in CMakeLists.txt:
  Target "gflags-shared" INTERFACE_INCLUDE_DIRECTORIES property contains
  relative path:

    "include"


CMake Error in CMakeLists.txt:
  Target "gflags_nothreads-shared" INTERFACE_INCLUDE_DIRECTORIES property
  contains relative path:

    "include"

```

Env:
 - Ubuntu-12.04
 - cmake-2.8.11.2

**Comment by soonhokong** [comment]
Related stackoverflow Q&A: http://stackoverflow.com/questions/25676277/cmake-target-include-directories-prints-an-error-when-i-try-to-add-the-source

**Comment by schuhschuh** [comment]
Thanks for pointing it out. I cannot see how it is related, though, because [gflags' ```CMakeLists.txt```](https://github.com/gflags/gflags/blob/d4e971c10b1557292b5371807a23921d15e7fece/CMakeLists.txt#L320) makes use of the generator expressions to deal with differing build and installation paths. I tested it with CMake 3.2.1 when I implemented it enabling all options. Thus, it may possibly be a problem of CMake itself, where the new ```INTERFACE_INCLUDE_DIRECTORIES``` property was maybe not well implemented yet in earlier versions that introduced it. I will try with CMake 2.8 and see how to fix it or require a newer CMake version.

**Comment by soonhokong** [comment]
One workaround is the following patch:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 778bb86..5f229fe 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -322,7 +322,7 @@ foreach (TYPE IN ITEMS STATIC SHARED)
             list (APPEND include_dirs "$<INSTALL_INTERFACE:${INCLUDE_INSTALL_DIR}>")
           endif ()
           target_include_directories (gflags${opts}-${type}
-            PUBLIC  "${include_dirs}"
+            PUBLIC  "$<INSTALL_INTERFACE:${include_dirs}>"
             PRIVATE "${PROJECT_SOURCE_DIR}/src;${PROJECT_BINARY_DIR}/include/${GFLAGS_INCLUDE_DIR}"
           )
         endif ()
```

I'm not sure that it can be a general solution for all versions of cmake (i.e. 2.x and 3.x).

**Comment by soonhokong** [comment]
BTW, thanks for the quick response!

**Comment by schuhschuh** [comment]
I receive no errors with CMake 2.8.12 . Your workaround does not allow the use of the gflags library without installation. Would you be able to confirm that it works with CMake 2.8.12 ? I think it would be suitable then to require this version at least.

**Comment by schuhschuh** [comment]
So, I can confirm the errors you got using CMake 2.8.11.2 . My suggestion is to change the minimum required CMake version to 2.8.12 as 2.8.11 seems to have some related bugs.

**Comment by soonhokong** [comment]
I see. I agree that is reasonable. Thanks for checking things.
