### ISSUE TITLE
Install instructions do not work on Mac OSx Yosemite

### ISSUE THREAD

**Issue by ChrisInIssaquah** [gflags/gflags#114]
I install CMake in my applications folder, and launched ccmake, but beyond that I can not make heads or tails of what you expect to happen.

The package looks interesting, but CMake is a technology that I don't see the point of.

**Comment by schuhschuh** [comment]
CMake has pretty much replaced the auto-tools as most often used build configuration tool for C/C++ projects. The point is to have a more intuitive and expressive language to configure the build and define dependencies. IMHO, it's far easier to use, extend, and learn than writing Makefiles or autoconf scripts for complex projects. The point is also to have a platform independent tool which then generates project files specific to the users platform and preferred build tool. From the CMakeLists.txt files, CMake can generate files for a number of popular and often used build tools, e.g., GNU Make, Ninja, MS Visual Studio, Eclipse, CodeBlocks, Xcode... and [many more](http://www.cmake.org/cmake/help/v3.0/manual/cmake-generators.7.html).

Given it's wide use nowadays, I might not have been specific enough on how to use CMake. I also think you are better referred to the CMake documentation itself: [Running CMake](http://www.cmake.org/runningcmake/)

To run the CMake GUI on Mac OS, just double click the CMake application bundle that you copied to "/Applications/CMake". The ```ccmake``` command which you can run in the Terminal offers another GUI-like interface (based on curses lib), but is not as friendly for newcomers. In the GUI, just press the "Configure" button once you set the "source" and "build" directory paths. Then you can click "Generate" to have CMake create the Xcode project files (assuming you chose the Xcode generator). You can then open the gflags.xcodeproject found in the "build" directory with Xcode.

If you prefer the command line (Terminal), you can also create Makefiles instead. For example,

```
git clone git@github.com:gflags/gflags.git
mkdir gflags/build
cd gflags/build
ccmake ..
# press 'c' to configure the project
# modify variables in the ccmake curses window
# press 'c' again if you changed any values
# press 'g' to generate the Makefiles and exit cam
make -j8
```
