### ISSUE TITLE
Using gflags as subproject

### ISSUE THREAD

**Issue by evgen231** [gflags/gflags#117]
I get errors whenever I try to use gflags as subproject.
```
CMake Error at CMakeLists.txt:7 (target_link_libraries):
  Target "gflags" of type UTILITY may not be linked into another target.  One
  may link only to STATIC or SHARED libraries, or to executables with the
  ENABLE_EXPORTS property set.
```

Minimal CMakeLists.txt.
```cmake
cmake_minimum_required (VERSION 3.2)
project (minimal)

add_subdirectory (gflags)

add_executable (minimal main.cpp)
target_link_libraries (minimal gflags)
```

As workaround I patched gflags/CMakeLists.txt with
```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index c32bce3..8207837 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -335,9 +335,10 @@ foreach (TYPE IN ITEMS STATIC SHARED)
           target_link_libraries (gflags${opts}-${type} shlwapi.lib)
         endif ()
         if (NOT TARGET gflags${opts})
-          add_custom_target (gflags${opts})
+          add_library (gflags${opts} ALIAS gflags${opts}-${type})
+        else ()
+          add_dependencies (gflags${opts} gflags${opts}-${type})
         endif ()
-        add_dependencies (gflags${opts} gflags${opts}-${type})
         list (APPEND TARGETS gflags${opts}-${type})
       endif ()
     endforeach ()
```

EDIT BY @schuhschuh: This patch is invalid and should not be used! Instead, use the following or substitute ```gflags``` by ```gflags_static``` or ```gflags_shared``` in your ```target_link_libraries``` command.
```cmake
add_subdirectory(gflags)
add_library(gflags ALIAS gflags_static)
```

**Comment by schuhschuh** [comment]
Nice, the ALIAS option of add_library must be new in CMake 3. Given that you have gflags as submodule in your project and thus should now which particular library you want to link to, you should have possibly used the particular library target instead in your target_link_libraries.

Do you want to send a PR for this change? Maybe using the ALIAS only when the CMake version does support it?

**Comment by schuhschuh** [comment]
Also, I wonder if when you integrate gflags this way if it would be good to set the options to be used in the gflags/CMakeLists.txt and avoid that these are then added to the CMake cache.

For example,
```cmake
set (gflags_BUILD_STATIC_LIBS ON)
add_subdirectory(gflags)
```
and whenever ```NOT gflags_SOURCE_DIR EQUAL CMAKE_SOURCE_DIR```, the gflags CMakeLists.txt should not add any CMake cache variables (i.e, not use the ```option``` command).

**Comment by evgen231** [comment]
ALIAS option appered at [CMake 2.8.12] (http://www.cmake.org/cmake/help/v2.8.12/cmake.html#command:add_library).

Options may be declared like this
```cmake
option (BUILD_STATIC_LIBS "..." OFF)
# ...
option (gflags_BUILD_STATIC_LIBS "..." ${BUILD_STATIC_LIBS})
```
I'm not sure that it's a good idea.

**Comment by schuhschuh** [comment]
I was rather thinking of:

```cmake
macro(gflags_option name doc default)
  if (gflags_SOURCE_DIR EQUAL CMAKE_SOURCE_DIR)
    option(${name} ${doc} ${value})
  elseif (NOT DEFINED ${name})
    set(${name} ${default})
  endif ()
endmacro ()
```

**Comment by schuhschuh** [comment]
> ALIAS option appered at CMake 2.8.12

Good, in that case we can require at least this CMake version and just use it.

**Comment by schuhschuh** [comment]
> The <target> may not be an IMPORTED target or an ALIAS.

This means, however, it can still not be used in the gflags-config.cmake file. So that part may not be affected by this change.

**Comment by AndrewTsao** [comment]
+1

**Comment by schuhschuh** [comment]
The "fix" by @madwyn is invalid. The custom ```gflags``` and/or ```gflags_nothreads``` targets are only meant for convenience when building the gflags library (e.g., to run ```make gflags``` instead of ```make gflags_static gflags_shared```). When using gflags as a submodule, you should know whether you want to link to the static or shared library. You can thus either use ```gflags_static``` or ```gflags_shared``` as link dependency of your targets or define an ALIAS target yourself for either one of these.

The more interesting aspect of this issue is to modify the ```CMakeLists.txt``` of gflags to not add any variables/options to the CMake cache when gflags is part of another project. Let it be this project's responsibility to set those CMake variables before adding the gflags subdirectory.

**Comment by schuhschuh** [comment]
The use of gflags as subproject is now possible. See [this example project](https://github.com/gflags/example) and PR #140.
