### ISSUE TITLE
Documentation: Incorrect git clone instructions

### ISSUE THREAD

**Issue by minh-t-nguyen** [gflags/gflags#118]
On http://gflags.github.io/gflags/#download

It currently says:

You can clone the project using the command:

     git clone git@github.com:gflags/gflags.git

However, that should be

     git clone https://github.com/gflags/gflags.git

**Comment by schuhschuh** [comment]
Both are correct, depending on which [protocol](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols) you prefer. Usually the Git protocol is preferred, but maybe it simply doesn't work for your setup.

**Comment by schuhschuh** [comment]
https://help.github.com/articles/which-remote-url-should-i-use/
