### ISSUE TITLE
Library not loaded: /usr/local/lib/libgflags.2.dylib

### ISSUE THREAD

**Issue by Coldmooon** [gflags/gflags#119]
I compiled glfags using `brew` on MAC several months ago. At that time, I can run [`Caffe`](https://github.com/BVLC/caffe) correctly. However, I have uninstalled `gflags` and reinstalled it by `brew install gflags` this week. After this, every time I run caffe's example, I got this error:
```
Library not loaded: /usr/local/lib/libgflags.2.dylib
```
In my /usr/local/lib, I have 
```
$ ls -l *gflags*
lrwxr-xr-x  1 Coldmoon  admin  38 Jul  1 17:06 libgflags.a -> ../Cellar/gflags/2.1.2/lib/libgflags.a
lrwxr-xr-x  1 Coldmoon  admin  48 Jul  1 17:06 libgflags_nothreads.a -> ../Cellar/gflags/2.1.2/lib/libgflags_nothreads.a
```
I don't know how to compile gflags's dynamic library by `brew`. Can anyone help me ? Many thanks!

**Comment by Coldmooon** [comment]
I've just compiled it manually from the source code. Now I have `libgflags.2.dylib`. But another error appears.
```
Incompatible library version: caffe.mexmaci64 requires version 4.0.0 or later, but libgflags.2.dylib provides version 2.0.0
```
The `gflags`' source code is the newest. How can I get libgflags.2.dylib of version 4.0

**Comment by supradeus** [comment]
same here
 
```
laptop-jegor:caffe7 jopdorp$ make runtest
awk: cmd. line:1: {exit  < 7.0;}
awk: cmd. line:1:        ^ syntax error
.build_release/tools/caffe
dyld: Library not loaded: /usr/local/lib/libgflags.2.dylib
  Referenced from: /Users/jopdorp/dev/machinelearning/caffe7/.build_release/lib/libcaffe.so
  Reason: Incompatible library version: libcaffe.so requires version 4.0.0 or later, but libgflags.2.dylib provides version 2.0.0
make: *** [runtest] Trace/BPT trap: 5
```

**Comment by schuhschuh** [comment]
> My gflags' source code is the newest (downloaded from here). How can I get libgflags.2.dylib of version 4.0

There is no such gflags version. As the ```2``` in the file name suggests, this gflags library has major version number 2. The question is rather why does libcaffe.so require a non-existing version and possibly this question can better be addressed by the Caffe developers.

**Comment by supradeus** [comment]
I ran make clean, make test and the make runtest again, it gave me the following error:

```
dyld: Library not loaded: /usr/local/lib/libgflags.2.dylib
  Referenced from: /usr/local/lib/libglog.0.dylib
  Reason: Incompatible library version: libglog.0.dylib requires version 4.0.0 or later, but libgflags.2.dylib provides version 2.0.0
```

I reinstalled glog:
```
brew reinstall glog
```

After that make runtest worked!

**Comment by wolframteetz** [comment]
Apologize for posting here, but when trying to run OpenCV 3.1 on OSX I get the same error

$ python
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/sir/.virtualenvs/cv/lib/python2.7/site-packages/cv2.so, 2): Library not loaded: /usr/local/lib/libgflags.2.dylib
  Referenced from: /usr/local/lib/libopencv_sfm.3.1.dylib
  Reason: Incompatible library version: libopencv_sfm.3.1.dylib requires version 4.0.0 or later, but libgflags.2.dylib provides version 2.0.0

Any ideas?

**Comment by drernie** [comment]
+1

**Comment by geekan** [comment]
+1

**Comment by nikhilsig** [comment]
This can be fixed by updating gflags (using brew), then uninstalling and reinstalling OpenCV3.0.

**Comment by paranoidpixel** [comment]
I had the same problem. I confirmed @nikhilsig comment by updating gflags and installing OpenCV (in this case I rebuild my OpenCV 3.1.0 from source). It's on an OSX machine.
