### ISSUE TITLE
gflags should provide a file for pkg-config 

### ISSUE THREAD

**Issue by igor-petruk** [gflags/gflags#120]

**Comment by schuhschuh** [comment]
Any interest in providing a template file that can be configured using CMake's configure_file command?

**Comment by davetcoleman** [comment]
+1... I think this is related, but in Ubuntu 14.04 LTS release of gflags it seems CMake is not properly configured. As in, there is no FindGflags.cmake so I have to use my own:
https://github.com/ros/cmake_modules/issues/36#issuecomment-124222187

**Comment by schuhschuh** [comment]
@davetcoleman  You shouldn't need a FindGflags.cmake file and none needs to be provided. The gflags package configures and installs a gflags-config.cmake file instead. This file is all CMake's find_package command requires and looks for. Usually the file is located in the "lib" directory, e.g., "lib/cmake". The gflags version shipped with Ubuntu 14.04 seems to be 2.0, however. This was before the transition to CMake. Thus, your problem would be resolved once the Ubuntu package manager moves to the new version and installs the gflags-config.cmake file in the appropriate location.

**Comment by davetcoleman** [comment]
That makes sense, though I am confused why libgflags2 installs the file
```
/usr/lib/x86_64-linux-gnu/libgflags.so.2.1.0
```
Wouldn't that mean its 2.1?

Do you know who released gflags into Ubuntu, and can we get the version bumped?

**Comment by schuhschuh** [comment]
> Do you know who released gflags into Ubuntu, and can we get the version bumped?

No, unfortunately not. I'm sure there must be information about this out there.

**Comment by schuhschuh** [comment]
The Ubuntu packages index suggests the Debian package maintainer is Koichi Akabe. A look at the Debian packages reveals there seems to be already one for the latest gflags version 2.1.2 (see https://packages.debian.org/stretch/libgflags2). You find the email addresses of the Debian package maintainers on this page.

**Comment by schuhschuh** [comment]
Unfortunately these packages don't seem to contain the required CMake configuration file: https://packages.debian.org/stretch/amd64/libgflags2/filelist

**Comment by davetcoleman** [comment]
Also note that I'm working on Ubuntu 14.04, which does not have 2.1.2:
http://packages.ubuntu.com/trusty/libs/libgflags2

**Comment by davetcoleman** [comment]
I'm guessing the

**Comment by schuhschuh** [comment]
I noted. But as this is the old gflags version which indeed provides a pkg-config file, there is nothing to be done. I think CMake contains modules to find packages using pkg-config. Newer Ubuntu versions will hopefully contain a new libgflags-dev package with the required gflags-config.cmake file. I've sent a message to Koichi to start a discussion.

**Comment by schuhschuh** [comment]
Closing this issue as gflags uses CMake and there is no need for a pkg-config file.

**Comment by eklitzke** [comment]
I would kindly ask that you consider re-opening this issue.

I understand that gflags itself does not need pkg-config because it uses CMake. However, I think you are missing the issue. Packages that are built using other build systems like autotools also do not need pkg-config files. The reason they provide them is it makes it **much** easier for others to use code that ships with `.pc` files.

As an example, I am working on a project internally at my company that is built using autotools that makes use of glog and gflags. I have the following lines in my `configure.ac` file:

```python
PKG_CHECK_MODULES(GLOG, libglog)
PKG_CHECK_MODULES(GFLAGS, libgflags)
```

This works on Debian and Ubuntu because they have patches that they apply to their gflags Debian build to provide a `.pc` file. However, I cannot get my code to compile under Fedora using this approach, because Fedora does not currently ship a `.pc` file for gflags.

Even if you ignore the autotools issue, pkg-config files make it really easy to build projects with regular Makefiles. For instance, it's common to see code like this in hand-crafted Makefiles:

```make
foo.o: foo.c
	$(CC) -std=c99 -fPIC $(shell pkg-config --cflags glib-2.0) $< -o $@
```

Makefiles built this way are easy to write and extremely portable. It allows people to use projects like without the need to know autotools, CMake, or even make itself.

**Comment by schuhschuh** [comment]
@eklitzke I would be fine if someone provided a respective template file that can be configured and installed with CMake as I noted in my initial reply. However, I have not received any PR regarding this. Feel encouraged to submit one :-).

Personally I have no interested spending the effort to provide such file for outdated build tools (which of course my still find widespread use in old software), also because of my insufficient experience with these. I also don't think you can call the use of Makefiles "portable"... that is exactly the reason why projects such as CMake and others have evolved. IMHO, writing Makefiles by hand is a somewhat archaic approach to building software...

**Comment by yurivict** [comment]
FYI Similar suggestion was closed as committed in 1.4: https://github.com/gflags/gflags/issues/50

What happened with it?

**Comment by jart** [comment]
Random Googler here. I just want to +1 what @eklitzke said. Installing a `.pc` file for pkg-config is just good open source citizenship. This is something Google is committed to doing.

There's absolutely no reason for a C++ library to not have one. Doing so only shifts the burden of writing a pkg-config to distro maintainers. Some of whom won't write one. Then it becomes impossible to rely on pkg-config for cross-platform installs. It only works if everyone does it. This has 

Please reconsider your decision @schuhschuh.

**Comment by schuhschuh** [comment]
@jart Thanks for the input. As you can see from my very first comment on this topic, I have no objection of *generating* such pkg-config file using CMake and was encouraging a PR from the Open Source community. Writing one by hand makes no sense given that the build system used by this Open Source gflags library is now CMake and many projects have already transitioned to it from other more archaic build systems. You will find many open source projects that use CMake and provide a so-called CMake configuration file such as `gflags-config.cmake` to be included by other CMake-based projects just like pkg-config works. Many of these don't provide a `.pc` file.

**Comment by schuhschuh** [comment]
To be clear, @jart and @eklitzke, I would much appreciate if either of you who expressed strong interest in this feature would provide a PR for configuring and installing such `.pc` file using CMake.

**Comment by jart** [comment]
> Personally I have no interested spending the effort to provide such file for outdated build tools (which of course may still find widespread use in old software) [...] archaic build systems

This also deserves comment. Make and Autotools are excellent. They are absolutely not antiquated. They stood the test of time. They are universally agreed upon tools with a clear consensus in the open source community. Developers who choose to use them, deserve to have their choices respected.

For example, I can see that this project ditched CMake for Bazel a few months ago. CMake didn't stand the test of time. But perhaps you should have considered Autotools. Heavyweight build systems are more appropriate for large projects and services. Not tiny libraries. Please consider that there are many "from source" install distros like Gentoo which you'll be slowing down by not using standard tooling.

I say this as someone who works on Bazel. I maintain http://github.com/bazelbuild/rules_closure. I think Bazel is the best build system in the world. The only one that offers an improvement over make & friends. But I also recognize when it's not the right tool for the job. And I would never act disrespect the traditional standard tools, which still play a very important role.

**Comment by schuhschuh** [comment]
> Developers who choose to use them, deserve to have their choices respected.

Absolutely, but as noted they are very welcome to contribute to this project to satisfy their needs. Respecting their choice doesn't mean that I have to be making the same choices. That's then not respecting my choice ;-).

> Bazel is the best build system in the world.

That may well be and as you can see I already accepted a PR which enables integration of gflags in Bazel although I, as a non-Googler, don't use it.

**Comment by yurivict** [comment]
There are many cmake-based projects that also provide .pc

See libgit2 https://github.com/libgit2/libgit2 and allegro https://sourceforge.net/projects/alleg/ , for example.

**Comment by schuhschuh** [comment]
>  I can see that this project ditched CMake for Bazel a few months ago.

You are mistaken. I accepted a PR to *also* make it easy for Bazel folks to integrate gflags. I would do the same for pkg-config as I repeated multiple times in this thread. But nobody who cares so much about these build tools was willing to contribute one. You could demonstrate your commitment of Google to provide pkg-config files by contributing to this project via a PR to generate such file.

**Comment by schuhschuh** [comment]
> There are many cmake-based projects that also provide .pc.

Of course and that is great. All I said is that you will find also counter-examples. That didn't exclude the inverse.

**Comment by jart** [comment]
@schuhschuh Writing a `.pc` is usually super simple and quick, but sometimes requires subtle knowledge to which only the project maintainer and platform-specific experts will be privvy. In this thread, you're already engaged with @vbkaisetsu who wrote the `.pc` for Debian. You've also got @yurivict above, who does packaging for FreeBSD. I'm sure you guys could figure it out a good unified approach in a couple hours, if you chose to do so.

**Comment by schuhschuh** [comment]
> Writing a .pc is usually super simple and quick.

I am certain that is true. Just as for many other build tools once you learned them, even if it only takes a few hours. For the past decades, I had no need to use Autotools in my own projects. Anyone who is experience with it and a user of gflags or package maintainer, please step forward and spend those "couple hours". PRs are always welcome as can be seen from past submissions.

**Comment by davetcoleman** [comment]
Let's not let this get too heated :-)

Thank all of you for your work in open source and in this project. I use CMake everyday as a user, but don't know how to write a ``.pc``. I did write a ``FindGflags.cmake`` a while back for the open source project [ROS](www.ros.org) - you can see it [here](https://github.com/davetcoleman/cmake_modules/blob/3b9dc467bdcdeaa36999de408e7d126a7a3ad701/cmake/Modules/FindGflags.cmake). Is that at all relevant?

**Comment by schuhschuh** [comment]
Reference `gflags.pc` file content from #50:
```
prefix=/usr/local
exec_prefix=/usr/local
libdir=/usr/local/lib
includedir=/usr/local/include

Name: gflags
Version: 1.3
Description: A commandline flags library that allows for distributed flags
URL: http://code.google.com/p/google-gflags
Requires:
Libs: -L${libdir} -lgflags
Libs.private: -pthread 
Cflags: -I${includedir}
```

**Comment by sboukortt** [comment]
It seems that the pkgconfig file is always installed, even when GFlags is included as a subproject. I assume that this is an oversight?

More specifically:

- `PKGCONFIG_INSTALL_DIR` is always set on non-Windows platforms: https://github.com/gflags/gflags/blob/1005485222e8b0feff822c5723ddcaa5abadc01a/CMakeLists.txt#L416-L435
- then, it is the only condition used to determine whether to install the file: https://github.com/gflags/gflags/blob/1005485222e8b0feff822c5723ddcaa5abadc01a/CMakeLists.txt#L573-L576

**Comment by schuhschuh** [comment]
Thanks for pointing this out. I tend to agree the pkgconfig file shouldn't be installed when gflags is a subproject of a consuming project.

**Comment by schuhschuh** [comment]
I've made the installation conditional on the `INSTALL_HEADERS` option, the same option that is used to decide whether or not to install a CMake package configuration file.

See 28f50e0fed19872e0fd50dd23ce2ee8cd759338e.
