### ISSUE TITLE
Unable to find libgflags.so.2.2.0

### ISSUE THREAD

**Issue by akshayc11** [gflags/gflags#121]
Hi,
I am facing an issue with the compiling of gflags 2.1.2:

```
Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:56 (FILE):
  file INSTALL cannot find
  "/nobackupp8/achandra/speech3/ext/gflags-src/build/lib/libgflags.so.2.2.0".
```

The command I am using for cmake is:
```
cmake -DBUILD_SHARED_LIBS="ON" -DBUILD_STATIC_LIBS="ON" -DGFLAGS_NAMESPACE="google" -DCMAKE_INSTALL_PREFIX=`pwd` ../ || exit 1;
make || exit 1;
make install || exit 1;
```

```
The output of the cmake command is:
-- The CXX compiler identification is GNU 4.7.3
... # removed unnecessary lines for brevity
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Check size of pthread_rwlock_t
-- Check size of pthread_rwlock_t - done
-- Configuring done
-- Generating done
-- Build files have been written to: /nobackupp8/achandra/speech3/ext/gflags-src/build
```

**Comment by schuhschuh** [comment]
I am not able to reproduce this error with the commands you provided. Are you sure the build step was successful? What version of CMake are you using?

**Comment by akshayc11** [comment]
I am using cmake version 2.8.12.2
Its an ubuntu 14.04 machine.

**Comment by akshayc11** [comment]
Here's what I observed: 
After performing make,
The lib folder looks like:

`
akshayc@ubuntu1404:/data-local1/akshayc/Workspace/Software/speech3/ext/gflags-2.1.2/build/lib $ ls -la
total 808
drwxrwxr-x 2 akshayc akshayc   4096 Feb 21 23:11 .
drwxrwxr-x 5 akshayc akshayc   4096 Feb 21 23:09 ..
-rw-rw-r-- 1 akshayc akshayc 250380 Feb 21 23:11 libgflags.a
-rw-rw-r-- 1 akshayc akshayc 250380 Feb 21 23:11 libgflags_nothreads.a
lrwxrwxrwx 1 akshayc akshayc     24 Feb 21 23:11 libgflags_nothreads.so -> libgflags_nothreads.so.2
lrwxrwxrwx 1 akshayc akshayc     28 Feb 21 23:11 libgflags_nothreads.so.2 -> libgflags_nothreads.so.2.1.2
-rwxrwxr-x 1 akshayc akshayc 154809 Feb 21 23:11 libgflags_nothreads.so.2.1.2
lrwxrwxrwx 1 akshayc akshayc     14 Feb 21 23:11 libgflags.so -> libgflags.so.2
lrwxrwxrwx 1 akshayc akshayc     18 Feb 21 23:11 libgflags.so.2 -> libgflags.so.2.1.2
-rwxrwxr-x 1 akshayc akshayc 154874 Feb 21 23:11 libgflags.so.2.1.2
`

But on performing make install,

`
total 656
drwxrwxr-x 2 akshayc akshayc   4096 Feb 21 23:12 .
drwxrwxr-x 5 akshayc akshayc   4096 Feb 21 23:09 ..
-rw-rw-r-- 1 akshayc akshayc 250380 Feb 21 23:11 libgflags.a
-rw-rw-r-- 1 akshayc akshayc 250380 Feb 21 23:11 libgflags_nothreads.a
lrwxrwxrwx 1 akshayc akshayc     24 Feb 21 23:11 libgflags_nothreads.so -> libgflags_nothreads.so.2
lrwxrwxrwx 1 akshayc akshayc     28 Feb 21 23:11 libgflags_nothreads.so.2 -> libgflags_nothreads.so.2.1.2
-rwxrwxr-x 1 akshayc akshayc 154809 Feb 21 23:11 libgflags_nothreads.so.2.1.2
lrwxrwxrwx 1 akshayc akshayc     14 Feb 21 23:11 libgflags.so -> libgflags.so.2
lrwxrwxrwx 1 akshayc akshayc     18 Feb 21 23:11 libgflags.so.2 -> libgflags.so.2.1.2
`

Any reason why make install deletes the file?

**Comment by schuhschuh** [comment]
It is not recommended to use the build directory as installation directory. When you want to skip installation because you are in a development (opposed to production/deployment) environment, you may use the build tree directly without installation step. Otherwise, please choose an installation prefix that differs from the build and source directories.
