### ISSUE TITLE
No license document

### ISSUE THREAD

**Issue by seanhoughton** [gflags/gflags#122]
What license is this code released under?

**Comment by schuhschuh** [comment]
Modified BSD. The license document is called ```COPYING```.

(cf. "In GNU programs the license is usually in a file called COPYING." in [this article](http://www.gnu.org/licenses/gpl-howto.en.html))

**Comment by davidzchen** [comment]
I think this article indicates that COPYING is used for programs that use the GNU licenses.

The common practice that I have seen for projects using other licenses seems to be to use a LICENSES file instead of COPYING.

**Comment by schuhschuh** [comment]
You may be right in regards the origin of the name COPYING and the link certainly suggests so, however, besides that it is standard to name this file either LICENSE or COPYING, there is no common "rule" as to what it has to be for any non-GNU software. People are familiar to look for either. Further, a look at the source file headers you use is always the best you can do...
