### ISSUE TITLE
Registering flag validators causes unused variable warning

### ISSUE THREAD

**Issue by Martin2112** [gflags/gflags#123]
I'm compiling code that uses gflags on platforms with compiler configs that treat warnings as errors. This produces errors like this on registering validators:

error: ‘{anonymous}::follow_dummy’ defined but not used [-Werror=unused-variable]
static const bool follow_dummy =
                   ^
cc1plus: all warnings being treated as errors

These are also flagged in Eclipse as "unused declaration".

I don't see an obvious way of avoiding these warnings each time a validator is registered. For portability reasons #prama and gcc atttributes are not ideal solutions. We could get people to build with  -Wno-error=unused-variable on affected platforms but this doesn't seem great either.

Is there an alternative? Thanks.

**Comment by schuhschuh** [comment]
When you use ```RegisterFlagValidator``` within your ```main``` module, you could avoid the warning by actually reading the value of the (static) variable which the return value was assigned.

```c++
#include <iostream>
#include <gflags/gflags.h>

static bool ValidatePort(const char* flagname, int32 value)
{
  if (value > 0 && value < 32768) return true;
  std::cerr << "Invalid value for --" << flagname << ": " << value << std::endl;
  return false;
}

DEFINE_int32(port, 0, "What port to listen on");
static bool port_validator_registered = RegisterFlagValidator(&FLAGS_port, &ValidatePort);

int main(int argc, char *argv[])
{
  if (!port_validator_registered) {
    cerr << "Failed to register port validator" << endl;
    exit(1);
  }
  gflags::ParseCommandLineFlags(argc, argv, true);
  return 0;
}
```

But in this case, I would suggest to call ```RegisterFlagValidator``` in the main function itself:
```c++
int main(int argc, char *argv[])
{
  if (!RegisterFlagValidator(&FLAGS_port, &ValidatePort)) {
    cerr << "Failed to register port validator" << endl;
    exit(1);
  }
  gflags::ParseCommandLineFlags(argc, argv, true);
  return 0;
}
```

So remains the question how to register a flag validator during static initialisation in another compilation unit and avoid the unused variable warnings. One solution could be to use the global variable in a dummy function:
```c++
static bool ValidatePort(const char* flagname, int32 value)
{
  if (value > 0 && value < 32768) return true;
  std::cerr << "Invalid value for --" << flagname << ": " << value << std::endl;
  return false;
}

DEFINE_int32(port, 0, "What port to listen on");
static bool port_validator_registered = RegisterFlagValidator(&FLAGS_port, &ValidatePort);

inline bool IsPortValidatorRegistered()
{
  return port_validator_registered;
}
```
The definition of such global function could be part of the ```DEFINE_validator``` macro.

**Comment by schuhschuh** [comment]
Respectively, I am wondering if the unused warning goes away when you use a (unnamed) namespace:
```c++
namespace {
  static bool port_validator_registered = RegisterFlagValidator(&FLAGS_port, &ValidatePort);
}
```
which may also explain why you don't seem to have an issue with the unused static ```FlagRegisterer``` variables added by the ```DEFINE_int32``` et al. macros. Do you?

**Comment by schuhschuh** [comment]
I've compiled the gflags/example project with GCC 6 on macOS installed via Homebrew that uses one flag validator with `-Wall` and `-Werror`, but it doesn't produce any unused variable warning.

**Comment by schuhschuh** [comment]
Marking this issue as resolved question. There was no further feedback since my previous suggestions and I cannot reproduce the warning.
