### ISSUE TITLE
third_party\gflags\src/mutex.h(352,17) :  error: using namespace directive in global context in header [-Werror,-Wheader-hygiene]

### ISSUE THREAD

**Issue by phthoruth** [gflags/gflags#124]
Build webrtc or libyuv with clang for windows
Compile error occurs in debug build

For webrtc
set GYP_DEFINES=clang=1 target_arch=ia32
python tools\clang\scripts\update.py
python webrtc\build\gyp_webrtc
ninja -k 9 -C out\Debug

For libyuv
set GYP_DEFINES=buildtype=Dev clang=1 target_arch=ia32 
python tools\clang\scripts\update.py
python gyp_libyuv -fninja -Gconfig=Debug libyuv_test.gyp
ninja -C out\Debug

ninja: Entering directory `out\Debug'
[32/34] CXX obj\third_party\gflags\src\gflags.gflags.obj
FAILED: ninja -t msvc -e environment.x86 -- "..\..\third_party/llvm-build/Release+Asserts/bin/clang-cl" -m32 /nologo /showIncludes /FC @obj\third_party\gflags\src\gflags.
gflags.obj.rsp /c ..\..\third_party\gflags\src\gflags.cc /Foobj\third_party\gflags\src\gflags.gflags.obj /Fdobj\third_party\gflags\gflags.cc.pdb
In file included from ..\..\third_party\gflags\src\gflags.cc:112:
..\..\third_party\gflags\src/mutex.h(352,17) :  error: using namespace directive in global context in header [-Werror,-Wheader-hygiene]
using namespace MUTEX_NAMESPACE;
                ^
..\..\third_party\gflags\src/mutex.h(158,25) :  note: expanded from macro 'MUTEX_NAMESPACE'
#define MUTEX_NAMESPACE gflags_mutex_namespace
                        ^
1 error generated.
[32/34] CXX obj\unit_test\libyuv_unittest.convert_test.obj

For libyuv, the release build works.
In third_party\gflags\gflags.gyp
the regular clang build disables the warning

# TODO(andrew): Look into fixing this warning upstream:
# http://code.google.com/p/webrtc/issues/detail?id=760
['clang==1', {
  'cflags!': ['-Wheader-hygiene',],
  'xcode_settings': {
    'WARNING_CFLAGS!': ['-Wheader-hygiene',],
  },
}],

But cflags is not used for clangcl on Windows.

**Comment by schuhschuh** [comment]
Thanks for reporting, moved the using statement to the including source file.

**Comment by phthoruth** [comment]
awesome! 
FYI As a work around with the current code, I passed the options like this:

'msvs_settings': {
  'VCCLCompilerTool': {
    'AdditionalOptions!': [
      '-Wheader-hygiene',  # Suppress warning about using namespace.
    ],
  },
},

It still doesnt build.  It used to, so I think new chromium common.gypi or something caused the breakage. So it would be good if you can try clang=1 builds on Windows/bots to keep things healthy.
I'll file a followup issue for the other build error.  Thanks!

**Comment by schuhschuh** [comment]
Can you give some details on the build error ? I was indeed not testing the change because I have no Windows system nearby. Thought the change was trivial enough...

**Comment by schuhschuh** [comment]
Ok, just noticed the other issue. So this isn't really related to the namespace warning.
