### ISSUE TITLE
third_party\gflags\src\gflags.cc(281,53) :  error: unused typedef 'true_false_equal' [-Werror,-Wunused-local-typedef]

### ISSUE THREAD

**Issue by phthoruth** [gflags/gflags#125]
Build libyuv with clang for windows:
Compile error occurs in debug build

set GYP_DEFINES=buildtype=Dev clang=1 target_arch=ia32 
python tools\clang\scripts\update.py
python gyp_libyuv -fninja -Gconfig=Debug libyuv_test.gyp
ninja -C out\Debug

gflags.obj.rsp /c ..\..\third_party\gflags\src\gflags.cc /Foobj\third_party\gflags\src\gflags.gflags.obj /Fdobj\third_party\gflags\gflags.cc.pdb
..\..\third_party\gflags\src\gflags.cc(281,53) :  error: unused typedef 'true_false_equal' [-Werror,-Wunused-local-typedef]
    COMPILE_ASSERT(sizeof(kTrue) == sizeof(kFalse), true_false_equal);
                                                    ^
1 error generated.

As a work around, add this to gflags.gyp
'msvs_settings': {
  'VCCLCompilerTool': {
    'AdditionalOptions': [
      '-Wno-unused-local-typedef',  # Suppress unused private typedef.
    ],
  },
},

**Comment by schuhschuh** [comment]
This code I used in another project could probably be used to fix this:

```c++
// Static assertion which does not cause GCC >=4.8 issue a unused local typedef warning
template <bool b> struct StaticAssert;
template <> struct StaticAssert<true>{};
```

**Comment by schuhschuh** [comment]
Should be fixed. No more warning with Xcode 7 on OS X.
