### ISSUE TITLE
snprintf when building with Visual Studio 2015

### ISSUE THREAD

**Issue by General-Fault** [gflags/gflags#127]
See chromium issue 440500 and webrtc issue 5183

The snprintf definition should be hidden behind a #ifdef _MSC_VER < 1900.

**Comment by General-Fault** [comment]
https://codereview.appspot.com/270690043

**Comment by robhshu** [comment]
This has already been fixed in #116.

**Comment by schuhschuh** [comment]
Thanks for referencing the merged pull request.
