### ISSUE TITLE
`gflags_unittest` fails?

### ISSUE THREAD

**Issue by strin** [gflags/gflags#136]
I just cloned from the master branch, changed the test flag in CMakeLists.txt to be `ON`, and run 

```
cmake .; make
```

Then running `./bin/gflags_unittest` gives error

```
ERROR: error parsing env variable 'BOOL_BAD1' with value 'so true!'
ERROR: error parsing env variable 'BOOL_BAD2' with value ''
ERROR: error parsing env variable 'INT_BAD1' with value 'one'
ERROR: error parsing env variable 'INT_BAD2' with value '100000000000000000'
ERROR: error parsing env variable 'INT_BAD3' with value '0xx10'
ERROR: error parsing env variable 'INT_BAD4' with value ''
ERROR: error parsing env variable 'INT_BAD1' with value 'one'
ERROR: error parsing env variable 'INT_BAD3' with value '0xx10'
ERROR: error parsing env variable 'INT_BAD4' with value ''
ERROR: error parsing env variable 'BIGINT_BAD1' with value '18446744073709551616000'
ERROR: error parsing env variable 'INT_BAD1' with value 'one'
ERROR: error parsing env variable 'INT_BAD3' with value '0xx10'
ERROR: error parsing env variable 'INT_BAD4' with value ''
ERROR: error parsing env variable 'BIGINT_BAD1' with value '18446744073709551616000'
ERROR: error parsing env variable 'DOUBLE_BAD1' with value '0.0.0'
ERROR: error parsing env variable 'DOUBLE_BAD2' with value ''
```

Any thoughts?

**Comment by schuhschuh** [comment]
The unit tests are executed via CTest, i.e.,

```shell
make test
```

or using the ```ctest``` binary when the build tool is not GNU Make.

```shell
ctest -C Release
```

I have moved the binaries to ```Testing/bin``` to "hide" them from the normal user.

**Comment by schuhschuh** [comment]
@strin I just noticed that the code from which the error messages are coming that you posted are enclosed in a ```#if GTEST_HAS_DEATH_TEST````. Maybe I have simply never run those tests myself...

**Comment by schuhschuh** [comment]
Note that the "Error" messages you are receiving are expected. These tests are supposed to ensure that the program recognises such incorrect environment variable values are terminates the program execution as a result of these (so called "death tests"). The Error messages are thus not alarming in this case, but desired.

**Comment by schuhschuh** [comment]
Had to revert the change of the test binary locations because it otherwise complicates the execution of the tests on Windows with a shared gflags library build. Would need to set the PATH before test execution...

**Comment by avrilzchen** [comment]
Is there a way to run the glfags_unittest test binary on a target without make test? It's giving me those errors mentioned here when I don't use CTest: https://github.com/gflags/gflags/issues/136#issue-136492547
