### ISSUE TITLE
valgrind reports multiple issues

### ISSUE THREAD

**Issue by arames** [gflags/gflags#138]
Tested with commit 3ae911f3e7eb2ed3f34017355dc5d829f411962b

Test program:

    #include <gflags/gflags.h>

    DEFINE_bool(verbose, false, "Verbose mode.");

    int main(int argc, char** argv) {
      std::string usage("test program");
      gflags::SetUsageMessage(usage);
      gflags::ParseCommandLineFlags(&argc, &argv, true);
      return 0;
    }

Compile the example with

    g++ main.cc -o main -lgflags -lpthread
    

Running this under valgrind shows multiple issues.

    valgrind --leak-check=full --show-leak-kinds=all ./main

    ==13377== Memcheck, a memory error detector
    ==13377== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
    ==13377== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
    ==13377== Command: ./main
    ==13377== 
    ==13377== 
    ==13377== HEAP SUMMARY:
    ==13377==     in use at exit: 2,947 bytes in 79 blocks
    ==13377==   total heap usage: 91 allocs, 12 frees, 3,273 bytes allocated
    ==13377== 
    ==13377== 7 bytes in 1 blocks are still reachable in loss record 1 of 79
    ==13377==    at 0x4C2BBA0: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
    ==13377==    by 0x5606429: strdup (strdup.c:42)
    ==13377==    by 0x406FB6: google::SetArgv(int, char const**) (in /home/aleram01/work/gflags/src/test/main)
    ==13377==    by 0x40A4DB: google::ParseCommandLineFlagsInternal(int*, char***, bool, bool) (in /home/aleram01/work/gflags/src/test/main)
    ==13377==    by 0x402C65: main (in /home/aleram01/work/gflags/src/test/main)

    [...]

    ==13377== 160 bytes in 1 blocks are still reachable in loss record 79 of 79
    ==13377==    at 0x4C2C100: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
    ==13377==    by 0x404299: google::(anonymous namespace)::FlagRegistry::GlobalRegistry() (in /home/aleram01/work/gflags/src/test/main)
    ==13377==    by 0x404D48: google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*) (in /home/aleram01/work/gflags/src/test/main)
    ==13377==    by 0x402D14: __static_initialization_and_destruction_0(int, int) (in /home/aleram01/work/gflags/src/test/main)
    ==13377==    by 0x402D2D: _GLOBAL__sub_I__ZN3fLB13FLAGS_verboseE (in /home/aleram01/work/gflags/src/test/main)
    ==13377==    by 0x4196FC: __libc_csu_init (in /home/aleram01/work/gflags/src/test/main)
    ==13377==    by 0x559B9CE: (below main) (libc-start.c:245)
    ==13377== 
    ==13377== LEAK SUMMARY:
    ==13377==    definitely lost: 0 bytes in 0 blocks
    ==13377==    indirectly lost: 0 bytes in 0 blocks
    ==13377==      possibly lost: 0 bytes in 0 blocks
    ==13377==    still reachable: 2,947 bytes in 79 blocks
    ==13377==         suppressed: 0 bytes in 0 blocks
    ==13377== 
    ==13377== For counts of detected and suppressed errors, rerun with: -v
    ==13377== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Comment by schuhschuh** [comment]
Thanks @arames for providing an example of this yet persisting memory leak. The same issue was also still present for the program version and program name strings. These were addressed by @MaxDZ8 in the ```bugfix/#51-memory-leaks``` branch (#51) long time ago, which uses ```std::string``` instead of ```const char *``` for these global variables and avoids the need for ```strdup```. However, the changes in this branch also changed the type of the string flags which breaks backwards compatibility and thus was never merged.

The memory leaks caused by the placement new of string flags (```DEFINE_string```) were fixed recently (cf. #51). I now pushed a commit which replicates @MaxDZ8 previous efforts to replace ```const char *``` by STL ```string```'s and thus avoids the use of ```strdup``` and the resulting memory leaks.

**Comment by schuhschuh** [comment]
P.S.: Note that you should call ```ShutDownCommandLineFlags``` at the end of ```main``` when you want to shut down the program cleanly for valgrind.

**Comment by arames** [comment]
Thanks!
Just after sending this issue I wondered if I was cleaning correctly. Thanks for the pointer.
After pulling, recompiling, and fixing as you suggested, it runs like a charm under valgrind.

**Comment by wesm** [comment]
Any timeline for 2.2.0? Ran into this valgrind issue today
