### ISSUE TITLE
VS2015 Compile Error

### ISSUE THREAD

**Issue by MikePelton** [gflags/gflags#146]
Compiling GFlags under Visual Studio 2015 fails with "snprintf already has a body" errors, presumably because VS2015 defines snprintf and previous versions didn't - the same issue pops up in Glog. To get it to build windows_port.cc needs a version test around its definition of snprintf thus:
```
#ifdef _MSC_VER
#if _MSC_VER < 1900 
int snprintf(char *str, size_t size, const char *format, ...) {
  int r;
  va_list ap;
  va_start(ap, format);
  r = vsnprintf(str, size, format, ap);
  va_end(ap);
  return r;
}
#endif
#endif
```

Thus far I can't confirm that this doesn't break anything, but it certainly allows the build to succeed.

**Comment by schuhschuh** [comment]
It seems [this incorrect preprocessor directive](https://github.com/gflags/gflags/blob/74bcd20c0e5b904a67e37abf0c1262824ff9030c/src/windows_port.cc#L47) is responsible. It should probably be a ```!defined(_MSC_VER) || _MSC_VER < 1900``` instead.

This older PR #116 actually fixed this issue earlier, but the following PR #129 messed it up.

**Comment by schuhschuh** [comment]
Actually, the it should be fine as is in the master branch. Was reading the preprocessor condition introduced by PR #129 incorrectly. Have you tried it with the master branch, @MikePelton?

**Comment by MikePelton** [comment]
Hi Andreas - I definitely took the 2.1.2 code rather than code from the master branch, so that would certainly explain what I'm seeing. Thanks for your very rapid response!
