### ISSUE TITLE
Failed build with bazel

### ISSUE THREAD

**Issue by apcode** [gflags/gflags#153]
Trying to build gflags as an external package with bazel but it fails.
My WORKSPACE file has:
git_repository(
    name = "gflags_git",
    commit = "546819b1d91d666c9e98a061fe2ff19f63cac9a7",
    remote = "https://github.com/gflags/gflags.git",
)
bind(
    name = "gflags",
    actual = "@gflags_git//:gflags",
## )

And I'm seeing this:

INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_root/37a5dd68e2cdecaca147bcf01bef232a/external/gflags_git/BUILD:94:1: declared output 'external/gflags_git/include/gflags/gflags.h' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely).
ERROR: /private/var/tmp/_bazel_root/37a5dd68e2cdecaca147bcf01bef232a/external/gflags_git/BUILD:94:1: declared output 'external/gflags_git/include/gflags/gflags_declare.h' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely).
ERROR: /private/var/tmp/_bazel_root/37a5dd68e2cdecaca147bcf01bef232a/external/gflags_git/BUILD:94:1: not all outputs were created.

**Comment by schuhschuh** [comment]
What system are you on? Can you try the [gflags-example](https://github.com/gflags/example) after possibly modifying the `WORKSPACE` file as below?

I've just tested it on both OS X 10.11 and Ubuntu 14.04. On Ubuntu, I needed to add pthreads to the link options. These result in a clang warning of an unused option on OS X, though. I am not clear yet how to conditionally add this link option only for Linux.

```
diff --git a/WORKSPACE b/WORKSPACE
index 2787c98..6835bb5 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -1,7 +1,7 @@
 git_repository(
     name   = "gflags_git",
-    commit = "5e3070670ff4e45be34ed721c9616d34d37f41f9",
-    remote = "https://github.com/gflags/gflags.git"
+    commit = "1d4fc3eeb55455c880b10f3aa378507c6855520e",
+    remote = "https://github.com/schuhschuh/gflags.git"
 )
 
 bind(
```
```
as12312@merapi:/homes/as12312/Code/gflags-example (master)
> bazel --output_base=/tmp/bazel build foo
.
WARNING: /tmp/bazel/external/gflags_git/WORKSPACE:1: Workspace name in /tmp/bazel/external/gflags_git/WORKSPACE (@__main__) does not match the name given in the repository's definition (@gflags_git); this will cause a build error in future versions.
INFO: Found 1 target...
Target //foo:foo up-to-date:
  bazel-bin/foo/foo
INFO: Elapsed time: 6.667s, Critical Path: 2.42s
```

In my case, I had to specify the `--output_base` because my home directory `/homes/as21312` is a NFS share, which resulted in some strange errors... (note that you most likely don't want to use `/tmp` for this, but a directory that persists rather).

**Comment by apcode** [comment]
RESOLVED.

The latest version of bagel worked fine.

**Comment by pmtischler** [comment]
I'm having the same error. How was this resolved?

**Comment by schuhschuh** [comment]
@pmtischler, @apcode noted the solution was to use the latest version of Bazel.
