### ISSUE TITLE
is it thread-safe if we change an flag value via ReparseCommandLineNonHelpFlags

### ISSUE THREAD

**Issue by countryhu** [gflags/gflags#169]
we want to hot-reload the flag value, for int and string type.
we change the values in flagfile and call ReparseCommandLineNonHelpFlags.

but in source code i see: #define SET_VALUE_AS(type, value)  VALUE_AS(type) = (value)

my question is:this function maybe unsafe for string type, some other thread reading the value when this thread is change the value.

**Comment by schuhschuh** [comment]
It should be thread safe because the command line parsing functions acquire the lock for all flags registered at the `FlagRegistry` singleton [here](https://github.com/gflags/gflags/blob/a69b2544d613b4bee404988710503720c487119a/src/gflags.cc#L1969).

**Comment by countryhu** [comment]
hi schuhschuh, 
thank you for your reply.

I see the lock when parsing and changing the flags(FLAGS_long_str) value, but there is no lock when read the FLAGS_long_str in my program.

my steps:
1. my code: DEFINE_string(long_str, "quit_quit_quit_quit_quit_quit_quit_quit_long_string", "test thread-safe");
2.change flagsfile. -long_str=quit_quit_quit_quit_quit_quit_quit_quit_long_string_append
3.call google::ReparseCommandLineNonHelpFlags to modify the FLAGS_long_str value

my puzzle:
when we acquired lock and changing FLAGS_long_str  [here](https://github.com/gflags/gflags/blob/master/src/gflags.cc#L268), at the same time another thread is reading the std::string concurrently. as we know, std::string is thread-unsafe，the read thread may cause some unexpected errors？

**Comment by schuhschuh** [comment]
You are right, reading the string directly in one thread while it is being updated by another thread can cause you troubles. Therefore, there exist these [setter/getter functions]( https://github.com/gflags/gflags/blob/7d31c02de8345d0a12010a0c1c8ebae37898f10e/src/gflags.h.in#L206). In particular, [GetCommandLineOption](https://github.com/gflags/gflags/blob/7d31c02de8345d0a12010a0c1c8ebae37898f10e/src/gflags.cc#L1629) uses a `FlagRegistryLock`.

**Comment by countryhu** [comment]
thank you, @schuhschuh 

reading the "string" directly in one thread while it is being updated by another thread can cause the thread-safe problem.

I want to confirm two questions:
1.for machine meta type:int32 int64 double, there is not the troubles, because  in my opinion the read/write is thread-safe.
2.if answer of question 1 is thread-hostile. 
if I want to write the double flag value  thread-safe , I must use api read CommandLineFlagInfo.current_value via GetCommandLineFlagInfo api. and parse current_value to double?

**Comment by schuhschuh** [comment]
It seems in your scenario, you cannot assume that any flag is not currently being updated by one thread while reading `FLAGS_` variable in another regardless of the type. This is because even for fundamental types the assignment of the potentially new value is [not necessarily atomic](http://stackoverflow.com/questions/1292786/is-updating-double-operation-atomic). You have to use the string based set/get API of the gflags library and convert between flag value and string representation, unless you can use your own thread synchronization which is more specific to your application.
