### ISSUE TITLE
how to unistall gflags-master completely?

### ISSUE THREAD

**Issue by flying-jack** [gflags/gflags#171]
"make unistall" just does not work, and i don't know how to unistall gflags-master installed by "make install" command. Many thanks

**Comment by schuhschuh** [comment]
When you installed gflags in a separate directory, e.g., `/opt/gflags`, you can just delete this entire directory. But if you chose `/usr/local` as CMAKE_INSTALL_PREFIX, you have to delete the installed files/subdirectories separately:

- `<prefix>/include/gflags`
- `<prefix>/lib/libgflags*.so`
- `<prefix>/lib/cmake/gflags`
