### ISSUE TITLE
Next release with VS build and valgrind fixes

### ISSUE THREAD

**Issue by sunsided** [gflags/gflags#172]
It appears that currently the 2.1.2 version cannot be built using Visual Studio 2015 due to the `snprintf` function already being defined, which results in errors like

```
gflags-2.1.2\src\windows_port.cc(62): error C2084: function 'int snprintf(char *const ,const std::size_t,const char *const ,...)' already has a body
```

I stumbled over this when trying to use gflags from the conan.io package (see https://github.com/eliaskousk/conan-gflags/issues/1).

A [required fix](https://github.com/gflags/gflags/blob/74bcd20c0e5b904a67e37abf0c1262824ff9030c/src/windows_port.h#L66) seems to be available, but sadly is not part of 2.1.2; could you release a hotfix package that includes it?

**Comment by schuhschuh** [comment]
It appears you implemented a work-around for now by using the master branch directly. Anyway, I've went through the open issues for the v2.2.0 release and there's only one minor left now (others post-poned). Will try to get it done soon and then make a new release.

**Comment by schuhschuh** [comment]
Update on the timeline for the next release (for @wesm, see #138): Sorry I couldn't get around wrapping it up till now. I'll allocate some time this weekend for a release.
