### ISSUE TITLE
[bazel build] Linking error due to not linking with pthread

### ISSUE THREAD

**Issue by robryk** [gflags/gflags#176]
When I compile gflags-example (as well as my own project), I get the following error:

```

robryk@iguatalpa:~/example$ bazel build ...
.
INFO: Found 1 target...
ERROR: /usr/local/google/home/robryk/example/foo/BUILD:1:1: Linking of rule '//foo:foo' failed: linux-sandbox failed: error executing command /usr/local/google/home/robryk/.cache/bazel/_bazel_robryk/0d0280d3a76251d432180c833ad92a5c/execroot/example/_bin/linux-sandbox ... (remaining 13 argument(s) skipped).
bazel-out/local-fastbuild/bin/external/gflags_git/libgflags.a(gflags.pic.o): In function `gflags_mutex_namespace::Mutex::Mutex()':
gflags.cc:(.text._ZN22gflags_mutex_namespace5MutexC2Ev[_ZN22gflags_mutex_namespace5MutexC5Ev]+0x39): undefined reference to `pthread_rwlock_init'
bazel-out/local-fastbuild/bin/external/gflags_git/libgflags.a(gflags.pic.o): In function `gflags_mutex_namespace::Mutex::Mutex(gflags_mutex_namespace::Mutex::LinkerInitialized)':
gflags.cc:(.text._ZN22gflags_mutex_namespace5MutexC2ENS0_17LinkerInitializedE[_ZN22gflags_mutex_namespace5MutexC5ENS0_17LinkerInitializedE]+0x3c): undefined reference to `pthread_rwlock_init'
bazel-out/local-fastbuild/bin/external/gflags_git/libgflags.a(gflags.pic.o): In function `gflags_mutex_namespace::Mutex::~Mutex()':
gflags.cc:(.text._ZN22gflags_mutex_namespace5MutexD2Ev[_ZN22gflags_mutex_namespace5MutexD5Ev]+0x2c): undefined reference to `pthread_rwlock_destroy'
bazel-out/local-fastbuild/bin/external/gflags_git/libgflags.a(gflags.pic.o): In function `gflags_mutex_namespace::Mutex::Lock()':
gflags.cc:(.text._ZN22gflags_mutex_namespace5Mutex4LockEv[_ZN22gflags_mutex_namespace5Mutex4LockEv]+0x20): undefined reference to `pthread_rwlock_wrlock'
bazel-out/local-fastbuild/bin/external/gflags_git/libgflags.a(gflags.pic.o): In function `gflags_mutex_namespace::Mutex::Unlock()':
gflags.cc:(.text._ZN22gflags_mutex_namespace5Mutex6UnlockEv[_ZN22gflags_mutex_namespace5Mutex6UnlockEv]+0x20): undefined reference to `pthread_rwlock_unlock'
collect2: error: ld returned 1 exit status
Target //foo:foo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.682s, Critical Path: 0.18s
```

Adding `linkopts = [ "-lpthread" ]` to the binary target I'm compiling works the problem around for me.

**Comment by schuhschuh** [comment]
Thanks, I've noted this also in #153, but had no time yet to look into how to fix this properly for both OS X (no need for `-lpthread`) and Linux (requires `-lpthread`):
> I've just tested it on both OS X 10.11 and Ubuntu 14.04. On Ubuntu, I needed to add pthreads to the link options. These result in a clang warning of an unused option on OS X, though. I am not clear yet how to conditionally add this link option only for Linux.

**Comment by robryk** [comment]
Would you mind sharing the warning that you get on OS X? For librt a POSIX-compliant compiler has to accept -lrt, even if librt is part of libc on a particular system. I'm not sure if it's not also the case for libpthread. If so, we might wish to just stomach the warning for now and file a bug against Clang.

**Comment by schuhschuh** [comment]
I'll have a look and will post if.

BTW: There's a branch with the fix where I was preparing a PR [in my fork](https://github.com/schuhschuh/gflags/tree/fix-bazel-build-pthread).

**Comment by schuhschuh** [comment]
Looking at it, I used `-pthread` instead of `-lpthread`... maybe that's the issue for clang?

**Comment by robryk** [comment]
Yes, POSIX specifies that a compiler has to understand `-lpthread`:

http://pubs.opengroup.org/onlinepubs/9699919799//utilities/c99.html (grep for "-l pthread")

It also seems that POSIX doesn't say anything about `-pthread`, while GCC manual says that this impacts both the preprocessor (?) and linker.

**Comment by schuhschuh** [comment]
Alright, thanks for clarifying. I'll change it to `-lpthread` then and push.

**Comment by snnn** [comment]
Hi friends,  

'-pthread' is always better than '-lpthread'. As @robryk said, '-pthread' impacts both the preprocessor and linker. If your program is a multi-threaded, then you should apply this flag to all source files at compile time, and link time.  When you add it, it really makes a difference. At least, '-pthread' implies '-D_REENTRANT=1'. Though the macro '_REENTRANT' is not very useful at nowadays, but, who knows what would happen if you forgot it.
