### ISSUE TITLE
New feature: allow optional conversion of dashes to underscores in flag names

### ISSUE THREAD

**Issue by toddlipcon** [gflags/gflags#177]
Most CLI tools outside of gflags tend to prefer delimiting words with dashes rather than underscores. So, users often will make a typo of "binary --foo-bar-baz" instead of "binary --foo_bar_baz".

gflags should have some option of auto-converting dashes in the flag name to underscores before looking for the flag.

**Comment by toddlipcon** [comment]
I'd be happy to write a patch for this, but would like one bit of guidance: does this need to be an optional feature for compatibility reasons? i.e do we need to introduce another flag like --gflags_convert_dashes which controls whether this behavior takes place? My gut feeling is that it's safe to do all the time, since it's impossible to define a flag with dashes today.

**Comment by schuhschuh** [comment]
> Most CLI tools outside of gflags tend to prefer delimiting words with dashes rather than underscores.

I second this as it's also my personal preference for option names.

> My gut feeling is that it's safe to do all the time, since it's impossible to define a flag with dashes today.

Agree. Don't see why dash and underscore couldn't be exchangeably. A bit like Python's `argparse` which automatically names the variable in the returned namespace with dashes replaced by underscores.

**Comment by schuhschuh** [comment]
Thanks for the PR.
