### ISSUE TITLE
Enable Bazel build on Windows

### ISSUE THREAD

**Issue by robryk** [gflags/gflags#179]
I'm getting the following error while compiling code that depends on gflags on Windows using Bazel:

```
INFO: Found 1 target...
ERROR: C:/tools/msys64/var/tmp/Bazel/rwpsBiIv/external/gflags_git/BUILD:7:1: undeclared inclusion(s) in rule '@gflags_git//:gflags':
this rule is missing dependency declarations for the following files included by 'external/gflags_git/src/gflags_reporting.cc':
  'C:/tools/msys64/var/tmp/Bazel/rwpsBiIv/external/gflags_git/src/windows_port.h'.
```

I depend on the gflags target in exactly the way the example project does and am using the current HEAD (ie. `cce68f0c9c5d054017425e6e6fd54f696d36e8ee`).

**Comment by schuhschuh** [comment]
Interesting that Bazel now supports Windows. This is yet declared "highly experimental", though. Regarding this error, I have to figure out how I can add source files based on the OS. Tried to use `os.name`, but importing the `os` module isn't possible it seems...

**Comment by schuhschuh** [comment]
I had some look, but I don't think I will be able to test this. For now, if you want to use gflags on Windows, you have to build it using CMake. To fix this, please consider submitting a PR after the upcoming 2.2 release (this weekend). I personally will not have time to make it work for Windows.

I assume the solution will involve the use of `select`. Also, Bazel itself must be built on Windows with the flag `--cpu=x86_windows_msvc`. There will need to be additional `srcs` be added (`windows_port.*`) and as well as link libraries such as `shlwapi.lib`. Further, `GFLAGS_IS_A_DLL` should be defined to either 1 or 0 depending on whether the library that is built is a shared library or a static library. Not clear how to solve that one given that Bazel seems to always built both a shared and a static library given the same `cc_library` rule.

**Comment by electronjoe** [comment]
I wanted to leave some updated Breadcrumbs for people using gFlags in windows under Bazel.

Just successfully built gFlags commit 9314597d4b742ed6f95665241345e590a0f5759b
- MS Visual Studios Community '17 (x64 toolchain)
- Bazel 0.4.5

I had to nail the -DHAVE_FNMATCH_H copts flag that was getting set in :bazel/gflags.bzl

Also, I think there is a type above (or things have changed). Bazel under Windows currently requires --cpu=x64_windows_msvc

**Comment by schuhschuh** [comment]
See also #243.

**Comment by schuhschuh** [comment]
Thanks @earhart for PR #246 closing this issue.

**Comment by earhart** [comment]
Ex-Googlers-who-can't-live-without-decent-tools FTW :-)
