### ISSUE TITLE
--helpshort complains about SetUsageMessage

### ISSUE THREAD

**Issue by schuhschuh** [gflags/gflags#18]
Original [issue 7](https://code.google.com/p/gflags/issues/detail?id=7) created by schuhschuh on 2007-08-31T16:11:33.000Z:

<b>What steps will reproduce the problem?</b>
1. Compile any short program with gflags without calling SetUsageMessage
2. Run the program with --helpshort

<b>What is the expected output? What do you see instead?</b>
A list of flags from the file containing main() only.  Instead, an error
message states 'Warning: SetUsageMessage() never called'.  If the
usage message is set, then I see the message I set it with as expected.

<b>What version of the product are you using? On what operating system?</b>
Version 0.6, Ubuntu linux x86-64

**Comment by moehuster** [comment]
> Comment [#1](https://code.google.com/p/gflags/issues/detail?id=7#c1) originally posted by schuhschuh on 2007-08-31T16:23:50.000Z:
> 
> <empty>

The original page has been moved and it can't be accessed.
