### ISSUE TITLE
undefined reference to `google::InitGoogleLogging(char const*)'

### ISSUE THREAD

**Issue by ramanpreet9** [gflags/gflags#182]
i am running a simple program:
`#include "glog/logging.h"

int main(int argc, char** argv) {

 google::InitGoogleLogging(argv[0]);

  return 0;

}
`

I am getting the following error:

MakeFiles/helloworld.dir/helloworld.cc.o: In function `main':
helloworld.cc:(.text+0x1a): undefined reference to `google::InitGoogleLogging(char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [helloworld] Error 1
make[1]: *** [CMakeFiles/helloworld.dir/all] Error 2
make: *** [all] Error 2

I installed and uninstalled and reinstalled gflags but i am at a loss why i cant compile a simple helloworld file. 

my cmake file:

cmake_minimum_required(VERSION 2.8)
 include_directories("/usr/include/gflags")  # manually added 

add_executable(helloworld helloworld.cc)
target_link_libraries(helloworld ceres)
set_target_properties(helloworld PROPERTIES LINKER_LANGUAGE CXX)

**Comment by schuhschuh** [comment]
I'm afraid you posted in the wrongame project. You are using `glog` the logging library. This here is `gflags` the command argument parsing library.
