### ISSUE TITLE
confirm if flags are set though the new value is not changed

### ISSUE THREAD

**Issue by countryhu** [gflags/gflags#183]
I want to confirm a scene.
When ReparseCommandLineNonHelpFlags, if all flags which assigned in the command line are set though the value is not changed.
if yes, could you add a check(only set value for different value) in [TryParseLocked](https://github.com/gflags/gflags/blob/master/src/gflags.cc#L852) function.

thank you.

**Comment by schuhschuh** [comment]
I am sorry, I have some difficulty understanding what you would like to do. Could you explain in some more detail and provide example code illustrating the desired behaviour?

**Comment by schuhschuh** [comment]
Closing assuming it has been resolved given no further response.
