### ISSUE TITLE
undefined reference to RestClient::Connection::Connection(std::string const&)

### ISSUE THREAD

**Issue by PacoElPirata** [gflags/gflags#204]
Hello everybody!

I am trying to use this library, but I need some help from you.

Here is the code I am trying to build.

---------------------------------------------------------------------------------------------------------------------------------
#include <iostream>
#include "connection.h"
#include "restclient.h"

int main(){

   RestClient::Response r = RestClient::get("www.google.es");
   std::cout << r.code;
   RestClient::init();
   RestClient::Connection* conn = new RestClient::Connection("www.google.es");
 
   return 0;
}
---------------------------------------------------------------------------------------------------------------------------------

The problem is that there is no problem using the  RestClient::get method, but however I cannot build any object of the RestClient::Connection class, so I cannot do the request I want.

The request I want to do needs to have a kind of special header, so I cannot do a normal get request to a single url.

Anybody know how could I fix it? I read it in the documentation and I have tried to check in the test, in order to follow the way it is done there, but is not running neither. I have included the path for the headers and added the library -l restclient-cpp, but I am wondering if the fail could be there, and it is not foud because of there is a different library wich contains it.

**Comment by schuhschuh** [comment]
Wrong forum/project. This is `gflags`, no REST client library.
