### ISSUE TITLE
Java Version

### ISSUE THREAD

**Issue by schuhschuh** [gflags/gflags#21]
Original [issue 10](https://code.google.com/p/gflags/issues/detail?id=10) created by schuhschuh on 2008-04-03T19:33:01.000Z:

After C and python, a Java version would be desirable.

**Comment by yin** [comment]
@schuhschuh I was working on a modular Args4j fork. I just found gflags and gflags-python and I'd like to follow the same design principles. Maybe you can have a look and tell me, what you think.

**Comment by schuhschuh** [comment]
Looks like a very nice Java package, @yin!

To consider this indeed a Java implementation of gflags rather than another command flags parsing library, I think it would need fullfill the following requirements, though:
- [x] Distributed flags with global flag registry (I believe that's what your [Flags](https://github.com/yin/java-flags/blob/master/src/main/java/com/github/yin/flags/Flags.java) class provides).
- [ ] Special flags: `-[-]flagfile`, `-[-]fromenv`, `-[-]tryfromenv`, and `-[-]undefok`.
- [ ] Boolean flags: `-[-]<name>` and `-[-]no<name>`.
- [ ] Support flag validators (cf. [gflags-python's annotation](https://github.com/google/python-gflags/blob/b4cf9cb32db200b3375e142ec8cffd9b2e46d48a/gflags/__init__.py#L161)).

A rather minor comment is that I would rename `Flags.init` to `Flags.parse` (the gflags-python function is called `gflags.parse`, the C++ function is called `ParseCommandLineFlags`).

**Comment by yin** [comment]
Thanks for your feedback.


Regards / S pozdravom

Matej Gagyi
