### ISSUE TITLE
missing release branch breaks yocto build

### ISSUE THREAD

**Issue by narrucmot** [gflags/gflags#218]
Has the "release" branch been removed recently?  This breaks yocto builds that fetch this gflags repo:
WARNING: gflags-2.1.2-r0 do_fetch: Failed to fetch URL git://github.com/gflags/gflags.git;branch=release, attempting MIRRORS if available
ERROR: gflags-2.1.2-r0 do_fetch: Fetcher failure: Unable to find revision 1a02f2851ee3d48d32d2c8f4d8f390a0bc25565c in branch release even from upstream
ERROR: gflags-2.1.2-r0 do_fetch: Fetcher failure for URL: 'git://github.com/gflags/gflags.git;branch=release'. Unable to fetch URL from any source.
ERROR: gflags-2.1.2-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /mnt/sdb/Projects/Andrew_Krenz/MiniZed/build/tmp/work/cortexa9hf-neon-xilinx-linux-gnueabi/gflags/2.1.2-r0/temp/log.do_fetch.31114
ERROR: Task (/mnt/sdb/Xilinx/PetaLinux/2017.1/components/yocto/source/arm/layers/meta-oe/recipes-support/gflags/gflags_2.1.2.bb:do_fetch) failed with exit code '1'

**Comment by schuhschuh** [comment]
I don't think recently. Not that I actually recall, but it must have been at least 6 months since... No external project should rely on a branch (other than `master` for the latest development version). Instead, refer to the specific commit SHA you are expecting.

**Comment by narrucmot** [comment]
Hi Andreas,

The filename of the yocto .bb file in my Xilinx PetaLinux installation indicates I am looking for version 2.1.2 of gflags.  Here are the contents of the bb recipe file:

DESCRIPTION = "The gflags package contains a C++ library that implements commandline flags processing. It includes built-in support for standard types such as string and the ability to define flags in the source file in which they are used"

HOMEPAGE = "https://github.com/gflags/gflags"

LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://COPYING.txt;md5=c80d1a3b623f72bb85a4c75b556551df"

SRC_URI = "git://github.com/gflags/gflags.git;branch=release"
SRCREV = "1a02f2851ee3d48d32d2c8f4d8f390a0bc25565c"
S = "${WORKDIR}/git/"

FILES_${PN}-dev += "${libdir}/cmake"

inherit cmake

EXTRA_OECMAKE="-DBUILD_SHARED_LIBS=ON"

PACKAGES =+ "${PN}-bash-completion"
FILES_${PN}-bash-completion += "${bindir}/gflags_completions.sh"
RDEPENDS_${PN}-bash-completion = "bash-completion"

How do I find the SHA info for the 2.1.2 release?

Thanks,
Tom

**Comment by schuhschuh** [comment]
Hi Tom,

the commit SHA is the SRCREV you posted. You can even click on the link GitHub created in your original post on their web site and it will take yout to the respective commit.

I would assume simply removing the brancheck specification from the repository URL would work. Assuming that the build tool will then automatically check out the specified SRCREV. It's the first time I hear of yocto, so no idea how it works or what it does.

Andreas

**Comment by schuhschuh** [comment]
So I've googled yocto SRCREV and it's as said. The URI should not include a branch specification when you don't use "${AUTOREF}" to get the latest branch commit. Thus, use

```SRC_URI = "git://github.com/gflags/gflags.git"```

**Comment by schuhschuh** [comment]
Can this issue be closed?
