### ISSUE TITLE
2.2.1 release?

### ISSUE THREAD

**Issue by v1bri** [gflags/gflags#220]
Any chance we could get a new release? Per [this thread](https://github.com/ruslo/hunter/pull/601) there was supposed to be v2.2.1 which would help close the Hunter fork but I guess it got lost along the way.

**Comment by schuhschuh** [comment]
Yes indeed. The question is have [these issues](https://github.com/ruslo/hunter/pull/601#issuecomment-263088299) been fixed? Also, I guess the reason I was holding off (besides being distracted by my studies) is that I would have liked #197 to be taken care of beforehand.

**Comment by v1bri** [comment]
Happy to look at those. What's the best way to kick off the builds so I can reproduce?

**Comment by schuhschuh** [comment]
These tests where run by @ruso as part of the hunter project. They're not
part of gflags.

**Comment by schuhschuh** [comment]
I think if you're working with MSVC and have version 2008, it would be helpful if you could have a look at the `INTTYPES_FORMAT` problem reported in #197. I believe that was the only real issue that remained.

**Comment by schuhschuh** [comment]
@v1bri I'm on it regarding the `INTTYPES_FORMAT` issue. I think actually that'll be all then before I can tag a 2.2.1 release.

**Comment by schuhschuh** [comment]
Release 2.2.1 is tagged.
