### ISSUE TITLE
Warnings/errors reported by PVS Studio

### ISSUE THREAD

**Issue by drillsar** [gflags/gflags#225]
OK I will change that line to that one Thanks.

Here is the errors:

- [ ] V550 An odd precise comparison. It's probably better to use a comparison with defined precision: fabs(A - B) < Epsilon. gflags.cc 422
- [ ] V522 There might be dereferencing of a potential null pointer 'tentative_value'. gflags.cc 813
- [ ] V575 The potential null pointer is passed into 'fread' function. Inspect the fourth argument. gflags.cc 1009
- [x] -V728 An excessive check can be simplified. The '||' operator is surrounded by opposite expressions 'arg[0] != '-'' and 'arg[0] == '-''.  gflags.cc line 1030
- [ ]  V769  The 'strrchr(type, ':')' pointer in the 'strrchr(type, ':') + 1' expression could be nullptr. In such case, resulting value will be senseless and it should not be used. gflags.cc 1408

**Comment by schuhschuh** [comment]
Well, technically
```
arg[0] != '-' || (arg[0] == '-' && arg[1] == '\0')
```
could be thought to be simplified to
```
arg[0] != '-' || arg[1] == '\0'
```
However, this would cause an issue for empty strings where `arg[0] == '\0'` and `arg[1] == '\0'` just by chance. So the error would be silenced by changing to
```
arg[0] != '\0' && (arg[0] != '-' || arg[1] == '\0')
```
But that always requires two comparisons and is not as natural as the first combination of tests. However, if it helps you can submit a PR to modify the check, making sure not to change the logic.

**Comment by schuhschuh** [comment]
Well, actually `!(arg[0] != '-')` is equivalent to `arg[0] == '-'` ... which already excludes an empty string. So yeah, guess the error is valid and it could be simplified to

```
arg[0] != '-' || arg[1] == '\0'
```

**Comment by drillsar** [comment]
OK I will change that line to that one Thanks.

more errors:

V575 The potential null pointer is passed into 'fread' function. Inspect the fourth argument. gflags.cc 1009
V522 There might be dereferencing of a potential null pointer 'tentative_value'. gflags.cc 813
V779 Unreachable code detected. It is possible that an error is present. gflags.cc 553

**Comment by schuhschuh** [comment]
Feel free to provide patches for errors you find in a single PR. Create a branch for these. I will review changes when submitted.

**Comment by drillsar** [comment]
V779 error has line:

```
const char* clean_name = filename() + strlen(filename()) - 1;
```
Which comes up unreachable code detected. Not sure if I seen that error before since the fix strncmp with empty kRootDir

**Comment by drillsar** [comment]
V550 An odd precise comparison. It's probably better to use a comparison with defined precision: fabs(A - B) < Epsilon. gflags.cc 422
I am always confused on comparing double and floats, but usually they are compared by a low value like the error suggests. Not sure though in this case would be needed.

**Comment by schuhschuh** [comment]
Actually, I didn't realize [this line](https://github.com/gflags/gflags/blob/4663c80d3ab19fc7d9408fe8fb22b07b87c76e5a/src/gflags.cc#L588) before. The previous change regarding `kRootDir` thus wasn't really needed because the code isn't reached indeed.

Good example for comparing double's is given here: https://stackoverflow.com/questions/4010240/comparing-doubles

The issue is that we cannot decide on a precision for the user of the library as we have no idea what the value is being used for. There would need to be a precision value for floating point flags that users could set. We could choose the smallest value `numeric_limits<double>::epsilon` by default.

**Comment by schuhschuh** [comment]
Regarding `CleanFileName`, it's probably best to get rid of this unexplained and unused code (#226). Implement new feature some time in the future maybe which is clearer and then understood.

**Comment by schuhschuh** [comment]
Installed latest PVS Studio version. Didn't produce the same warnings as shown above. Fixed two other minor warnings (cf. #266). Ignoring warnings relating to usage of `getenv`, `putenv`, and `Mutex` c'tor.
