### ISSUE TITLE
setenv function conflicts with gflags

### ISSUE THREAD

**Issue by RamsaySummer** [gflags/gflags#228]
Hello, 
I tried to compile gflags with Mingw. But as soon as I compile with mingw32-make. 

> C:\ceres\gflags-bin>mingw32-make
> Scanning dependencies of target gflags_static
> [ 10%] Building CXX object CMakeFiles/gflags_static.dir/src/gflags.cc.obj
> In file included from C:/ceres/gflags-bin/include/gflags/config.h:110:0,
>                  from C:\ceres\gflags-master\src\gflags.cc:90:
> C:/ceres/gflags-master/src/windows_port.h: In function 'void setenv(const char*, const char*, int)':
> C:/ceres/gflags-master/src/windows_port.h:80:13: error: ambiguating new declaration of 'void setenv(const char*, const char*, int)'
>  inline void setenv(const char* name, const char* value, int) {
>              ^~~~~~
> In file included from c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\cstdlib:75:0,
>                  from c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\stdlib.h:36,
>                  from C:/ceres/gflags-master/src/windows_port.h:56,
>                  from C:/ceres/gflags-bin/include/gflags/config.h:110,
>                  from C:\ceres\gflags-master\src\gflags.cc:90:
> c:\mingw\include\stdlib.h:837:30: note: old declaration 'int setenv(const char*, const char*, int)'
>  __cdecl __MINGW_NOTHROW  int setenv( const char *__n, const char *__v, int __f )
>                               ^~~~~~
> CMakeFiles\gflags_static.dir\build.make:62: recipe for target 'CMakeFiles/gflags_static.dir/src/gflags.cc.obj' failed
> mingw32-make[2]: *** [CMakeFiles/gflags_static.dir/src/gflags.cc.obj] Error 1
> CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/gflags_static.dir/all' failed
> mingw32-make[1]: *** [CMakeFiles/gflags_static.dir/all] Error 2
> Makefile:150: recipe for target 'all' failed
> mingw32-make: *** [all] Error 2

I also tried building with/without shared. I don't know how remove this issue. Is it impossible to compile with mingw? 

System information

Operating System => Windows10 64 Bit
Compiler => Mingw32_6.3
Cmake => 3.9.0-rc3

**Comment by schuhschuh** [comment]
MinGW had no `setenv` function declared before in `stdlib.h`. Hence, a custom wrapper is declared by the `windows_port.h` of gflags. It appears newer MinGW have a `setenv` function now. From the [comments in `stdlib.h` of MinGW](https://sourceforge.net/p/mingw/mingw-org-wsl/ci/baddeff0bb85a2054392eb93292f21436d8db1f4/tree/mingwrt/include/stdlib.h):
```c++
#if _POSIX_C_SOURCE >= 200112L
/* setenv() and unsetenv() are also available, from POSIX.1-2001 onwards.
 */
```

Hence, the same preprocessor condition should be used in gflags' `windows_port.h`.

Could you try to change the source code in `windows_port.h` [here](https://github.com/gflags/gflags/blob/aa2d0f7b4ed11849f40c3a1dc573ac331ebdaebd/src/windows_port.h#L80) as follows and let me know if that works?
```c++
#if !defined(_POSIX_C_SOURCE) || _POSIX_C_SOURCE < 200112L
inline void setenv(const char* name, const char* value, int) {
  // [...]
}
#endif

**Comment by schuhschuh** [comment]
If it fixes the issue, please consider submitting it as PR.

**Comment by RamsaySummer** [comment]
Yes it fixes the issue thanks schuhschuh

**Comment by schuhschuh** [comment]
Commit from 2016-11-28 where `setenv` was added to `stdlib.h` of MinGW:
https://sourceforge.net/p/mingw/mingw-org-wsl/ci/baddeff0bb85a2054392eb93292f21436d8db1f4/

**Comment by schuhschuh** [comment]
Accidentally referred to the wrong issue from merged PR.
