### ISSUE TITLE
how can i parse a file in program using gflags API, not through command line.

### ISSUE THREAD

**Issue by lqniunjunlper** [gflags/gflags#231]
how can i parse a file in program using gflags API, not through command line.

**Comment by schuhschuh** [comment]
@lqniunjunlper Sorry for the late response. I assume you refer to parsing command-line options given in a so-called `flagfile` that you can provide on the command-line of your program using the special `--flagfile` option. One option you have is to append this option with the path of your configuration file to the `argv` list that you pass to `ParseCommandLineFlags`.
