### ISSUE TITLE
Make compile pass with -Werror

### ISSUE THREAD

**Issue by sumit-g** [gflags/gflags#236]
Our env. by default treats warnings as errors. gflags today does not compile if -Werror flag is used.

**Comment by schuhschuh** [comment]
Please consider submitting a PR with the required changes to silence warnings you encounter.

**Comment by schuhschuh** [comment]
See also #225/#227 if you are on Windows.

**Comment by sumit-g** [comment]
Can you merge the PR. I believe all tests have passed.
