### ISSUE TITLE
The file "gflags-config.cmake" is installed

### ISSUE THREAD

**Issue by shlomyli** [gflags/gflags#238]
Installed "gflags" 2.1.2-3 binary by `sudo apt-get install libgflags-dev` 
but the file file `gflags-config.cmake` was not installed. 
Solved by compiling from source.

**Comment by schuhschuh** [comment]
Thanks @shlomyli for reporting this issue. I am aware that the binary distribution packages so far exclude the CMake package configuration file (`gflags-config.cmake`) which is installed as part of the CMake-generated `install` target when you configure the build yourself. This decision is up to the binary package maintainers and should rather be reported to, for example, the Debian/Ubuntu package maintainers. I have no influence on this decision.

Note, however, that newer binary packages appear to include all CMake configuration files. See for example [this Debian package](https://packages.debian.org/sid/amd64/libgflags-dev/filelist).
