### ISSUE TITLE
googletest.h:100: undefined reference to `google::FlagRegisterer::FlagRegisterer<int>([...])'

### ISSUE THREAD

**Issue by jianhuaixie** [gflags/gflags#240]
/usr/local/glog-0.3.5/src/googletest.h:100: undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
collect2: error: ld returned 1 exit status
Makefile:1079: recipe for target 'logging_unittest' failed
make: *** [logging_unittest] Error 1

**Comment by uuudown** [comment]
I think you should download gflags, compile and install. This works for me. I guess this is due to the different gcc version when compiling gflags and the one are building.

**Comment by uuudown** [comment]
I mean download the source code of gflags to install. https://github.com/gflags/gflags

**Comment by schuhschuh** [comment]
Closing this as duplicate of #203 (although your error appears to corresponds to an earlier revision where the `FlagRegisterer` constructor was not a template function).

**Comment by MirrorLakr** [comment]
I download gflag from github to reinstall. But it doesn't work. So what should I do?
