### ISSUE TITLE
How can I remove the symbol table from the generated so

### ISSUE THREAD

**Issue by yunfeiyang1989** [gflags/gflags#245]
Now I am doing the work to reduce the size of libgflags.so generated by compiling the source files,however,I have set the CMAKE_CXX_FLAGS and CMAKE_C_FLAGS in CMakeLists.txt like this:

SET(CMAKE_C_COMPILER "/usr/bin/aarch64-linux-gnu-gcc") 
SET ( CMAKE_C_FLAGS "-O3" CACHE STRING "compile flags" FORCE)

SET(CMAKE_CXX_COMPILER "/usr/bin/aarch64-linux-gnu-g++-5") 
SET ( CMAKE_CXX_FLAGS "-O3 -std=c++11" CACHE STRING "compile flags" FORCE)

I'm trying to remove the symbol table from the so file by using -O3,but it have no effect......

Does this need some other settings to remove the symbol table?Is there anyone handling this problem?

**Comment by schuhschuh** [comment]
Does [this blog post](https://www.technovelty.org/linux/stripping-shared-libraries.html) help?

**Comment by yunfeiyang1989** [comment]
Thank you,I tried the command:
$ # strip --strip-all ./libgflags.so 
strip: Unable to recognise the format of the input file `./libgflags.so'
It looks like the so file can't be recognised.....
My so file is generated by using the arm64 compiler, is there any difference ?

**Comment by schuhschuh** [comment]
Sorry for the late reply and that `strip` didn't work. I hope you found a working solution in the meantime. As this does not seem a gflags specific question, and I am unfamiliar with ARM, I suggest you direct your more general question of how to strip off the symbol table from ARM binaries to a more suitable audience.
