### ISSUE TITLE
cmake config after installation via apt

### ISSUE THREAD

**Issue by gladilov-gleb** [gflags/gflags#248]
Firstly, thanks for your great work! Actually I don't know should I write there or not, so, please redirect me if I'm wrong.

If I install gflags via apt package on Ubuntu 16.04

```bash
sudo apt install libgflags-dev
```

there is no any `gflags-config.cmake` file, so if I use cmake to build the project with some line like this:

```cmake
find_package(gflags REQUIRED)
```

I have an error that `gflags-config.cmake` not found.
If build library from sources there is no any issue.

**Comment by niosus** [comment]
That is because the version in the repo is old and does not contain the pkg-config. The apt repo seems to not have an update since 2015.

**Comment by gladilov-gleb** [comment]
@niosus, thank you for explanation.
Is any solution planned in the future?

**Comment by niosus** [comment]
I am not part of this project, so I have no idea. It seems that the current way it to include gflags as a subproject into cmake. We have to ask @schuhschuh if he knows anything about the possiblity to update the binary versions in the apt repo.

**Comment by gladilov-gleb** [comment]
@niosus, thanks a lot for help.

**Comment by niosus** [comment]
Also related #238

**Comment by schuhschuh** [comment]
Hi, the binary packages for distributions such as Ubuntu/Debian are maintained by different people. From the upstream project (this source project) side, both pkg-config and CMake are supported to make it easy to integrate gflags with your project. To support use of binary packages that the user can install via `apt-get`, you should include a `Findgflags.cmake` (or `FindGflags.cmake`) file in your own project and point the `CMAKE_MODULE_PATH` to where it is located in your project's source tree.

This Find module can first try to call `find_package` in the MODULE mode to look for `gflags-config.cmake`. If not found, fall back to look for the pkg-config configuration file, i.e., use [FindPkgConfig](https://cmake.org/cmake/help/v3.0/module/FindPkgConfig.html) module capabilities. As last resort, you can look for include path and library files with the respective CMake functions.

If you wrote such Find module, I would appreciate a pull request to include it here for others.

**Comment by schuhschuh** [comment]
Maybe have a look at the Find module included with Ceres:
https://ceres-solver.googlesource.com/ceres-solver/+/1.12.0/cmake/FindGflags.cmake

**Comment by niosus** [comment]
Thanks @schuhschuh the pointer to ceres is very helpful.
I have opened a bug for the package in the apt to bump its version in xenial repository to at least 2.2. See the bug here: https://bugs.launchpad.net/ubuntu/+source/gflags/+bug/1752114
