### ISSUE TITLE
Remove use of bind() in the bazel install

### ISSUE THREAD

**Issue by samliu** [gflags/gflags#251]
https://github.com/bazelbuild/bazel/issues/1952

Bind is considered harmful according to the official Bazel docs and usage is discouraged.

**Comment by schuhschuh** [comment]
Thanks for making aware of this. Note that this project doesn't use `bind`. You may be referring to the `gflags-example` project? Would you be able to submit a PR for that other project in the `gflags` GitHub group and update the docs here? Thanks.
