### ISSUE TITLE
Release gflags 2.2.2

### ISSUE THREAD

**Issue by drigz** [gflags/gflags#256]
At  time of writing there are [11 commits](https://github.com/gflags/gflags/compare/v2.2.1...master) on master since 2.2.1 (July 2017). These include https://github.com/gflags/gflags/commit/57ceb0ecc8bf5c129bf99fa9472b25342daecf9e, which is very useful for Bazel users, as it avoids leaking the private `config.h` header to users of gflags.

What do you think about issuing a 2.2.2 release, and possibly updating [the docs](https://gflags.github.io/gflags/#bazel) to refer to the tagged release (`tag = "2.2.2"`)?

**Comment by schuhschuh** [comment]
Reasonable given that's been more than another year since the last release. I should find time for this before the end of this month. Poke me here again if the release isn't available yet around the 25th...

**Comment by schuhschuh** [comment]
I'm free today and will try and get the release out. Thanks for the remainder!

**Comment by schuhschuh** [comment]
Merged in a number of outstanding pull requests and applied some fixes to these. Considering to include #257 in release, but may drop it from this one.

**Comment by schuhschuh** [comment]
Ready to finalize release:
- [ ] Update version in `CMakeLists.txt`
- [ ] Update ChangeLog
- [ ] Update README
- [ ] Update `doc`: `gflags::gflags` CMake import target
- [ ] Signed release tag (cf. #210)
- [ ] GitHub release note

**Comment by vershov** [comment]
@schuhschuh Andreas, any plans on it?

**Comment by schuhschuh** [comment]
All minor bug fixes that should go into this release are done. Only need to update the docs before tagging the release. Sorry it took this long. Just been changing jobs... Release should be out this weekend.

**Comment by schuhschuh** [comment]
Version 2.2.2 of gflags is now released. Sorry again for the delay!
