### ISSUE TITLE
Win(msvc) Unicode Bug

### ISSUE THREAD

**Issue by CruiseYoung** [gflags/gflags#257]
file: src\gflags.cc
line:1345

Fixes:
#elif defined(HAVE_SHLWAPI_H)
            || PathMatchSpecA(glob.c_str(), ProgramInvocationName())
            || PathMatchSpecA(glob.c_str(), ProgramInvocationShortName())
#endif

**Comment by schuhschuh** [comment]
Could you provide more details? What is the error? Do you have a working fix?

**Comment by schuhschuh** [comment]
Putting this on hold as no further details have been provided.

**Comment by dreamer-dead** [comment]
I guess that there can be a compilation error when `const char*` from `c_str()` is passed to the `PathMatchSpec` WinAPI.
`PathMatchSpec` is a macro which can be [`PathMatchSpecA`](https://docs.microsoft.com/en-us/windows/desktop/api/shlwapi/nf-shlwapi-pathmatchspeca) or `PathMatchSpecW` depending on `_UNICODE` macro.
Using `PathMatchSpecA` seems reasonable to me if the gflags itself do not use or define `_UNICODE` macro.

**Comment by schuhschuh** [comment]
Thanks @dreamer-dead for clarifying. I didn't notice the original post contained the suggested fix of using `PathMatchSpecA` instead of `PathMatchSpec`.
