### ISSUE TITLE
gflags triggers -Wmissing-variable-declarations

### ISSUE THREAD

**Issue by rnburn** [gflags/gflags#262]
I get the warning
```
main.cpp:50:1: warning: no previous extern declaration for
      non-static variable 'FLAGS_nomax_spans_per_second' [-Wmissing-variable-declarations]
DEFINE_int32(max_spans_per_second, 0,
```

even if I use `DECLARE_int32`. Could `DECLARE_int32` and others be modified to also declare the `FLAGS_no...` variables?

**Comment by schuhschuh** [comment]
Thanks for reporting! I think the proper resolution would be to add the keyword `static` to the declaration of this variable in `DEFINE_VARIABLE` macro, as users are not expected/allowed to access flags via `FLAGS_no<name>` variables.

**Comment by joprice** [comment]
I still see this when using master.

**Comment by biodranik** [comment]
The warning is still there.
