### ISSUE TITLE
export flags from shared libraries

### ISSUE THREAD

**Issue by huangqinjin** [gflags/gflags#267]
I always build my shared libraries with `-fvisibility=hidden` to hide all symbols by default as same as Windows DLL. Flags are exported from DLL but not SO/DSO due to the definition of `GFLAGS_DLL_DECLARE_FLAG` is empty rather than `__attribute__((visibility("default")))`.

`GFLAGS_IS_A_DLL` should indicate that the library is built as SHARED or STATIC, but now it always set to 0 in `INTERFACE_COMPILE_DEFINITIONS` other than Windows DLL.

**Comment by huangqinjin** [comment]
I think the following may be better.

`gflags.h`:
```
#ifndef GFLAGS_DLL_DEFINE_FLAG
#  if GFLAGS_IS_A_DLL
#    ifdef _MSC_VER
#      define GFLAGS_DLL_DEFINE_FLAG __declspec(dllexport)
#    else
#      define GFLAGS_DLL_DEFINE_FLAG __attribute__((visibility("default")))
#    endif
#  else
#    define GFLAGS_DLL_DEFINE_FLAG
#  endif
#endif
```

`CMakeLists.txt`:
```
target_compile_definitions (gflags_static PUBLIC GFLAGS_IS_A_DLL=0)
target_compile_definitions (gflags_shared PUBLIC GFLAGS_IS_A_DLL=1)
```

**Comment by schuhschuh** [comment]
@huangqinjin Thanks for reporting this and suggesting a solution. Can you have a look at PR #270 and check if this looks good?

Note that `GFLAGS_IS_A_DLL` is intentionally always `0` for Linux systems. Only a Windows `.dll` is a DLL. It does not mean whether the library is shared or static.
