### ISSUE TITLE
/usr/bin/ld: cannot find -lgflags::gflags

### ISSUE THREAD

**Issue by kk2491** [gflags/gflags#272]
Hi,

I am quite new to cmake and GFLAGS, kindly help me in fixing the below issue.

I have written a simple code to understand how ```GFLAG``` works. Below is the source code.

test_1.h
```
#include <gflags/gflags.h>
DECLARE_bool(sample_bool);
DECLARE_double(sample_double);
DECLARE_string(sample_string);
DECLARE_int32(sample_int);
```

test_1.cc
```
#include "include/test_1.h"
DEFINE_bool(sample_bool, true, "Sample bool initial value");
DEFINE_double(sample_double, 10.01, "Sample double initial value");
DEFINE_string(sample_string, "This is the sample string", "Sample string initial value");
DEFINE_int32(sample_int, 99, "Sample int initial value");
```

main_1.cc
```
#include "include/test_1.h"
#include <iostream>
using namespace std;
int main()
{
	cout << "Lets start the gflags test...!!!!";
	cout << "Sample bool value is   : " << FLAGS_sample_bool;
	cout << "Sample double value is : " << FLAGS_sample_double;
	cout << "Sample string value is : " << FLAGS_sample_string;
	cout << "Sample int value is    : " << FLAGS_sample_int;
}
```
CMakeLists.txt
```
cmake_minimum_required(VERSION 2.8) 
PROJECT(Example_1)

set(NAME_SRC
	src/main_1.cc
	src/test_1.cc	
)

set(NAME_HEADERS       
    include/test_1.h
)

find_package(gflags REQUIRED)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -std=c++0x")

include_directories(${CMAKE_CURRENT_SOURCE_DIR})
link_directories(${CMAKE_BINARY_DIR}/bin)
set(EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR}/bin)
add_executable(test_1 ${NAME_SRC})

target_link_libraries(test_1 gflags::gflags)

```

I am able to do ```cmake .``` successfully, however when I try to run ```make```, program gives the below error.

```
kk-ABC-0037:~/Example_1$ sudo make
[ 33%] Linking CXX executable bin/test_1
/usr/bin/ld: cannot find -lgflags::gflags
collect2: error: ld returned 1 exit status
CMakeFiles/test_1.dir/build.make:120: recipe for target 'bin/test_1' failed
make[2]: *** [bin/test_1] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/test_1.dir/all' failed
make[1]: *** [CMakeFiles/test_1.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

Could you please help me here.

Thank you,
KK

**Comment by schuhschuh** [comment]
Which version of the gflags library are you using? For versions prior to v2.2.2, the imported target name is just `gflags`, i.e., without the `gflags::` prefix. Can you try with

```
target_link_libraries(test_1 gflags)
```

**Comment by schuhschuh** [comment]
Also, just in general, please note that you should not include the "include" folder in an #include directive.

I would change your example source files to:

```
#include "test_1.h"
// [...]
```

And the CMakeLists.txt file to:

```
cmake_minimum_required(VERSION 2.8) 
project(Example_1)

set(SRCS
  src/main_1.cc
  src/test_1.cc	
)

set(HDRS       
  include/test_1.h
)

find_package(gflags REQUIRED)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -std=c++0x")

# Either set CMAKE_EXECUTABLE_OUTPUT_PATH prior to add_executable
set(CMAKE_EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR}/bin)

add_executable(test_1 ${SRCS} ${HDRS})

# Or set EXECUTABLE_OUTPUT_PATH target property afterwards (recommended)
set_target_properties(test_1 PROPERTIES EXECUTABLE_OUTPUT_PATH "${CMAKE_BINARY_DIR}/bin")
target_link_libraries(test_1 gflags)
```

**Comment by kk2491** [comment]
> Which version of the gflags library are you using? For versions prior to v2.2.2, the imported target name is just `gflags`, i.e., without the `gflags::` prefix. Can you try with
> 
> ```
> target_link_libraries(test_1 gflags)
> ```

@schuhschuh Thank you so much, it worked fine after changing it to only ```gflags```. I was following the documentation from https://gflags.github.io/gflags/. 

Thank you,
KK

**Comment by kk2491** [comment]
> Also, just in general, please note that you should not include the "include" folder in an #include directive.
> 
> I would change your example source files to:
> 
> ```
> #include "test_1.h"
> // [...]
> ```
> 
> And the CMakeLists.txt file to:
> 
> ```
> cmake_minimum_required(VERSION 2.8) 
> project(Example_1)
> 
> set(SRCS
>   src/main_1.cc
>   src/test_1.cc	
> )
> 
> set(HDRS       
>   include/test_1.h
> )
> 
> find_package(gflags REQUIRED)
> 
> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -std=c++0x")
> 
> # Either set CMAKE_EXECUTABLE_OUTPUT_PATH prior to add_executable
> set(CMAKE_EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR}/bin)
> 
> add_executable(test_1 ${SRCS} ${HDRS})
> 
> # Or set EXECUTABLE_OUTPUT_PATH target property afterwards (recommended)
> set_target_properties(test_1 PROPERTIES EXECUTABLE_OUTPUT_PATH "${CMAKE_BINARY_DIR}/bin")
> target_include_directories(test_1 PRIVATE "${CMAKE_SOURCE_DIR}/include")
> target_link_libraries(test_1 gflags)
> ```

Thanks for the suggestions. I would definitely follow this in next programs. 

I have a weird/silly doubt, lets consider I have 2 flag files ```flagfile1.txt``` and ```flagfile2.txt```, based on certain condition I need to select the flagfile accordingly. Is there a way this can be done without running the executable again?

This can be done by redefining the flag value in program, however if I get a way to replace the flag file completely that would be great.

Kindly excuse if you think this question is silly. 

Thank you,
KK

**Comment by schuhschuh** [comment]
I think the initially reported issue was resolved. Closing issue.

Regarding your follow-up question, sorry I never replied.
