### ISSUE TITLE
CMake Error at CMakeLists.txt:282 (message):

### ISSUE THREAD

**Issue by Amorness** [gflags/gflags#274]
CMake Error at CMakeLists.txt:282 (message):
  Do not know how to define a 32-bit integer quantity on your system! Neither
  uint32_t, u_int32_t, nor __int32 seem to be available.  Set
  [GFLAGS_]INTTYPES_FORMAT to either C99, BSD, or VC7 and try again.

-- Configuring incomplete, errors occurred!
See also "/home/parallels/phxqueue/third_party/gflags/CMakeFiles/CMakeOutput.log".
See also "/home/parallels/phxqueue/third_party/gflags/CMakeFiles/CMakeError.log"

**Comment by leizhu1989** [comment]
@Amorness  I have the save problem ,have you solve it?

**Comment by XiGou** [comment]
I just got a similar issue, And that's how I resolved it:

I got this info first:

```
CMake Error at CMakeLists.txt:282 (message):
Do not know how to define a 32-bit integer quantity on your system! Neither
uint32_t, u_int32_t, nor _int32 seem to be available. Set
[GFLAGS]INTTYPES_FORMAT to either C99, BSD, or VC7 and try again.

-- Configuring incomplete, errors occurred!
See also "/home/parallels/phxqueue/third_party/gflags/CMakeFiles/CMakeOutput.log".
See also "/home/parallels/phxqueue/third_party/gflags/CMakeFiles/CMakeError.log"
```

Then I checked `CMakeError.log`, search the key word `stdint.h`( because  uint_32 defined in stdint.h ), and I saw:

```
Determining if the include file stdint.h exists failed with the following output:
Change Dir: /root/zbs/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/ninja-build cmTC_54880 && [1/2] Building CXX object CMakeFiles/cmTC_54880.dir/CheckIncludeFile.cxx.o
[2/2] Linking CXX executable cmTC_54880
FAILED: cmTC_54880
: && /usr/bin/c++ -march=sandybridge -mtune=haswell -g3 -ggdb3 -O1 -fsanitize=address -static-libasan CMakeFiles/cmTC_54880.dir/CheckIncludeFile.cxx.o -o cmTC_54880   && :
/usr/bin/ld: cannot find -lasan
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
so the "Do not know how to define a 32-bit integer quantity on your system! Neither " is misleading

The real root cause is there is no asan static library in my system


I installed libasan-static, resolved.
