### ISSUE TITLE
gflags_define <var> takes precedence over GFLAGS_<var>

### ISSUE THREAD

**Issue by Mizux** [gflags/gflags#277]
# Context
- Using gflags as subproject i.e. `GFLAGS_IS_SUBPROJECT`  is `TRUE`
- Want to build and install **only** the shared lib with headers
- super project (pseudo) <root>/CMakeLists.txt:
```cmake
cmake_minimum_required (VERSION 3.5)
project(meta VERSION 1.0.0 LANGUAGES NONE)

# well in reality I define all of this in `external` directory and 
# I add_subdirectory() it from <root>/CMakeLists.txt
# here I simplify the layout putting everything here
set(BUILD_SHARED_LIBS OFF) 

set(GFLAGS_NAMESPACE "gflags")
set(GFLAGS_INSTALL_HEADERS ON)
set(GFLAGS_BUILD_SHARED_LIBS ON)
set(GFLAGS_INSTALL_SHARED_LIBS ON)
set(GFLAGS_BUILD_STATIC_LIBS OFF)
set(GFLAGS_INSTALL_STATIC_LIBS OFF)
add_subdirectory(gflags)

# contains executable foo with target_link_libraries(foo gflags::gflags)
add_subdirectory(foo) 
```

# Observed
* no install are generated
* `gflags_nothreads_static` is built.
* alias `gflags::gflags` point on it

# Expected
* install rules for headers and shared libs (i.e. `gflags_nothread` is in `install(TARGETS ...)`)
* `gflags::gflags` point to `gflags_nothread`

# Hypothese
IMHO the problem is, properties doesn't check GFLAGS_XXXX define
see
https://github.com/gflags/gflags/blob/524b83d0264cb9f1b2d134c564ef1aa23f207a41/CMakeLists.txt#L179-L182
and then you use unprefixed variables
https://github.com/gflags/gflags/blob/524b83d0264cb9f1b2d134c564ef1aa23f207a41/CMakeLists.txt#L199-L201
and
https://github.com/gflags/gflags/blob/524b83d0264cb9f1b2d134c564ef1aa23f207a41/CMakeLists.txt#L442

We should use `if (GFLAGS_BUILD_${TYPE}_LIBS)` instead.

# Side Topics (half related)
subproject default value seems to be out of sync (i.e. last column for INSTALL_XXX should match BUILD_XXX) IMHO
see
https://github.com/gflags/gflags/blob/524b83d0264cb9f1b2d134c564ef1aa23f207a41/CMakeLists.txt#L167-L168
and
https://github.com/gflags/gflags/blob/524b83d0264cb9f1b2d134c564ef1aa23f207a41/CMakeLists.txt#L174-L175

here: you build by default in STATIC only **but** want to install shared libs only...

## Proposal
What's about
```cmake
gflags_define (BOOL BUILD_SHARED_LIBS
  "Request build of shared libraries."
  OFF OFF)
gflags_define (BOOL BUILD_STATIC_LIBS
  "Request build of static libraries (default if BUILD_SHARED_LIBS is OFF)."
  OFF ON)
gflags_define (BOOL INSTALL_SHARED_LIBS
  "Request installation of shared libraries."
  ${GFLAGS_BUILD_SHARED_LIBS}  ${GFLAGS_BUILD_SHARED_LIBS})
gflags_define (BOOL INSTALL_STATIC_LIBS
  "Request installation of static libraries."
  ${GFLAGS_BUILD_INSTALL_LIBS}  ${GFLAGS_BUILD_INSTALL_LIBS})
```

**Comment by Mizux** [comment]
Reading the macro `gflags_define()`  I can fix it using:
```cmake
unset(BUILD_SHARED_LIBS)
```
before `add_subdirectory(gflags)`.

**Comment by schuhschuh** [comment]
Thanks @Mizux for reporting this. The use of non-prefixed variables in the root CMakeLists.txt is indeed intentional. This is to have the read the same variables regardless of whether gflags is a subproject or configured as separate project. The variables defined with `gflags_define` are initialized to the value of their respective `GFLAGS_` prefixed variable values if these are defined or set to a constant default value otherwise.

For a non-subproject built, these variables are cached, and thus once you modify them after the first run of CMake, the value of the `GFLAGS_` variables will not affect the value of these cached variables any longer. For a subproject built (`GFLAGS_IS_SUBPROJECT`), these variables are not added to the cache to not expose them to the end-user of your project. So in your case, the `GFLAGS_` variables should indeed always be the respective value that the variables defined by `gflags_define` are set to when this command is encountered.

You should not have to `unset(BUILD_SHARED_LIBS)`.

Can you add the following line right after the `gflags_define` invocations at [this line](https://github.com/gflags/gflags/blob/524b83d0264cb9f1b2d134c564ef1aa23f207a41/CMakeLists.txt#L183):
```
message("gflags: BUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}")
```

What is the output in your case? It should be whichever value `GFLAGS_BUILD_SHARED_LIBS` is set to before `add_subdirectory(gflags)`, i.e., `ON` in your case.

Further, it is worthwhile to check the value of `GFLAGS_IS_SUBPROJECT` at [this point](https://github.com/gflags/gflags/blob/524b83d0264cb9f1b2d134c564ef1aa23f207a41/CMakeLists.txt#L137). You could also explicitly `set(GFLAGS_IS_SUBPROJECT ON)` in your top-level CMakeLists.txt.

**Comment by schuhschuh** [comment]
Oh, I see now. It's because of the following in `gflags_define`:

```
if (NOT DEFINED ${varname})
  set (${varname} "${GFLAGS_${varname}}")
endif ()
```

This was indeed intentional, as to initialize these gflags-specific variables based on what you would pass/add to the cache when configuring it as separate project. However, I am wondering given your use case whether this was the right way to handle it...

**Comment by schuhschuh** [comment]
How about changing the logic of `gflags_define` such that the `GFLAGS_` variables always take precedence:

```
macro (gflags_define type varname docstring default)
  # note that ARGC must be expanded here, as it is not a "real" variable
  # (see the CMake documentation for the macro command)
  if ("${ARGC}" GREATER 5)
    message (FATAL_ERROR "gflags_variable: Too many macro arguments")
  endif ()
  if (NOT DEFINED GFLAGS_${varname})
    if (DEFINED ${varname})
      set(GFLAGS_${varname} "${varname}")
    else ()
      if (GFLAGS_IS_SUBPROJECT AND "${ARGC}" EQUAL 5)
        set (GFLAGS_${varname} "${ARGV4}")
      else ()
        set (GFLAGS_${varname} "${default}")
      endif ()
    endif ()
  endif ()
  if (GFLAGS_IS_SUBPROJECT)
    set (${varname} "${GFLAGS_${varname}}")
  else ()
    set (${varname} "${GFLAGS_${varname}}" CACHE ${type} "${docstring}")
  endif ()
endmacro ()
```

When `GFLAGS_BUILD_SHARED_LIBS` is not defined, but `BUILD_SHARED_LIBS` is defined, then the value of the latter will be used. Otherwise, `BUILD_SHARED_LIBS` under the `gflags` subdirectory is set to the value of `GFLAGS_BUILD_SHARED_LIBS`.

Would this behavior be more transparent/intuitive?

**Comment by Mizux** [comment]
Using `GFLAG_XXX` unconditionally when defined is better IMHO. Especially if super project set `XXX` for its own need but want to overload XXX for gflags.

So yes I agree with your proposal

**Comment by schuhschuh** [comment]
Could you give it a try with branch of PR #278 (`fix-gflags-define`) and/or review the change before I merge it in?

**Comment by Mizux** [comment]
I'm creating a pet example right now, i'll upload here and in PR the result (by adding few message STATUS) before after your patch.

Wait and see ;)

**Comment by schuhschuh** [comment]
If you feel motivated, it could be nice to add such example use with assertions as part of the unit tests.

See directory (test/config)[https://github.com/gflags/gflags/tree/master/test/config] for an example on how to test the CMake configuration. You could probably use `add_subdirectory` and point it to the root of the same source tree to mimic subproject use.

**Comment by Mizux** [comment]
First thing first, 1) test what we have now, 2) tst your PR, 3) find time to add UT

# Current Status
## Setup
I create a pet job like below
CMakeLists.txt:
```cmake
cmake_minimum_required (VERSION 3.5)
project(meta VERSION 1.0.0 LANGUAGES NONE)

# well in reality I define all of this in `external` directory and
# I add_subdirectory() it from <root>/CMakeLists.txt
# here I simplify the layout putting everything here
set(BUILD_SHARED_LIBS OFF)

set(GFLAGS_NAMESPACE "gflags")
set(GFLAGS_INSTALL_HEADERS ON)
set(GFLAGS_BUILD_SHARED_LIBS ON)
set(GFLAGS_INSTALL_SHARED_LIBS ON)
set(GFLAGS_BUILD_STATIC_LIBS OFF)
set(GFLAGS_INSTALL_STATIC_LIBS OFF)
add_subdirectory(gflags)

get_target_property(ALIASED gflags::gflags ALIASED_TARGET)
message("gflags::gflags alias target: ${ALIASED}")

# contains executable foo with target_link_libraries(foo gflags::gflags)
add_subdirectory(foo)
```

foo/CMakeList.txt:
```
project(foo LANGUAGES CXX)
add_executable(foo main.cpp)
target_link_libraries(foo gflags::gflags)
```
note: main.cpp contains `int main() {return 0;}`

GFlags hack:
```shell
git clone gflags....
cd gflags && git diff -U 
```
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 657a1f4..15aed91 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -175,6 +175,8 @@ gflags_define (BOOL INSTALL_SHARED_LIBS        "Request installation of shared l
 gflags_define (BOOL INSTALL_STATIC_LIBS        "Request installation of static libraries."                                ON  OFF)
 gflags_define (BOOL REGISTER_BUILD_DIR         "Request entry of build directory in CMake's package registry."            OFF OFF)
 gflags_define (BOOL REGISTER_INSTALL_PREFIX    "Request entry of installed package in CMake's package registry."          ON  OFF)
+message("gflags: BUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}")
+message("gflags: BUILD_STATIC_LIBS=${BUILD_STATIC_LIBS}")
 
 gflags_property (BUILD_STATIC_LIBS   ADVANCED TRUE)
 gflags_property (INSTALL_HEADERS     ADVANCED TRUE)
@@ -457,6 +459,7 @@ foreach (TYPE IN ITEMS STATIC SHARED)
     foreach (opts IN ITEMS "" _nothreads)
       if (BUILD_gflags${opts}_LIB)
         set (target_name "gflags${opts}_${type}")
+        message("gflags: Add library: ${target_name}")
         add_library (${target_name} ${TYPE} ${GFLAGS_SRCS} ${PRIVATE_HDRS} ${PUBLIC_HDRS})
         set_target_properties (${target_name} PROPERTIES
           OUTPUT_NAME "gflags${opts}${type_suffix}"
```
## Observed
```shell
cmake -H. -Bbuild
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
gflags: BUILD_SHARED_LIBS=OFF
gflags: BUILD_STATIC_LIBS=OFF
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include inttypes.h
-- Looking for C++ include inttypes.h - found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include sys/stat.h
-- Looking for C++ include sys/stat.h - found
-- Looking for C++ include fnmatch.h
-- Looking for C++ include fnmatch.h - found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Looking for strtoll
-- Looking for strtoll - found
gflags: Add library: gflags_nothreads_static
gflags::gflags alias target: gflags_nothreads_static
-- Configuring done
CMake Error: INSTALL(EXPORT) given unknown export "gflags-targets"
CMake Error: INSTALL(EXPORT) given unknown export "gflags-targets"
-- Generating done
-- Build files have been written to: /tmp/foo/build
```

## Analyze
As supposed `BUILD_SHARED_LIBS` take precedence over `GFLAGS_BUILD_SHARED_LIBS`
side effect: `INSTALL(EXPORT)` seems to break also (to investigate)

Next step do the same with your PR

**Comment by Mizux** [comment]
# TEST 2
Same as above **BUT** with:
```
unset(BUILD_SHARED_LIBS)
```

```shell
cmake -H. -Bbuild
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
gflags: BUILD_SHARED_LIBS=ON
gflags: BUILD_STATIC_LIBS=OFF
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include inttypes.h
-- Looking for C++ include inttypes.h - found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include sys/stat.h
-- Looking for C++ include sys/stat.h - found
-- Looking for C++ include fnmatch.h
-- Looking for C++ include fnmatch.h - found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Looking for strtoll
-- Looking for strtoll - found
gflags: Add library: gflags_nothreads_shared
gflags::gflags alias target: gflags_nothreads_shared
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/foo/build
```

note: each time I `rm -rf build`

**Comment by schuhschuh** [comment]
After `git clone`, do you `git checkout fix-gflags-define`?

**Comment by Mizux** [comment]
nop, not yet, this will be the next test ;)

**Comment by schuhschuh** [comment]
Ok, so you expected those tests to be negative...

**Comment by Mizux** [comment]
# Test 3
```shell
cd gflags
git stash # to keep my message
git fetch
git checkout fix-gflags-define
git stash apply # reapply my message patch
```
note: I also use `set(BUILD_SHARED_LIBS OFF)` as in TEST `#1`

```shell
cmake -H. -Bbuild
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
gflags: BUILD_SHARED_LIBS=ON
gflags: BUILD_STATIC_LIBS=OFF
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include inttypes.h
-- Looking for C++ include inttypes.h - found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include sys/stat.h
-- Looking for C++ include sys/stat.h - found
-- Looking for C++ include fnmatch.h
-- Looking for C++ include fnmatch.h - found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Looking for strtoll
-- Looking for strtoll - found
gflags: Add library: gflags_nothreads_shared
gflags::gflags alias target: gflags_nothreads_shared
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/foo/build
```

-> Seems to work as "expected" according to the new behaviour :fireworks:

**Comment by schuhschuh** [comment]
Thanks for testing it out!
