### ISSUE TITLE
/usr/bin/ld: cannot find -lgflags_static

### ISSUE THREAD

**Issue by 1gen100** [gflags/gflags#281]
Hey, I am trying to get the handeye_calib_camodocal code running but I can't seem to get it working because of a recurring error that I can't debug, hope you can help me.

~/catkin_ws$ catkin_make

Base path: /home/student/catkin_ws
Source space: /home/student/catkin_ws/src
Build space: /home/student/catkin_ws/build
Devel space: /home/student/catkin_ws/devel
Install space: /home/student/catkin_ws/install
Running command: "make cmake_check_build_system" in "/home/student/catkin_ws/build"
Running command: "make -j8 -l8" in "/home/student/catkin_ws/build"

[ 0%] Built target std_msgs_generate_messages_lisp
[ 0%] Built target std_msgs_generate_messages_nodejs
[ 0%] Built target std_msgs_generate_messages_cpp
[ 0%] Built target std_msgs_generate_messages_eus
[ 0%] Built target std_msgs_generate_messages_py
[ 13%] Built target kinect2_registration
[ 13%] Built target _beginner_tutorials_generate_messages_check_deps_Num
[ 13%] Built target _beginner_tutorials_generate_messages_check_deps_AddTwoInts
[ 16%] Linking CXX executable /home/student/catkin_ws/devel/lib/handeye_calib_camodocal/handeye_calib_camodocal
[ 26%] Built target beginner_tutorials_generate_messages_eus
[ 33%] Built target beginner_tutorials_generate_messages_cpp
[ 40%] Built target beginner_tutorials_generate_messages_lisp
[ 53%] Built target beginner_tutorials_generate_messages_py
[ 60%] Built target kinect2_calibration
[ 66%] Built target kinect2_bridge
[ 73%] Built target kinect2_bridge_nodelet
[ 80%] Built target beginner_tutorials_generate_messages_nodejs
[ 86%] Built target talker
[ 93%] Built target listener
[ 93%] Built target beginner_tutorials_generate_messages
/usr/bin/ld: cannot find -lgflags_static
collect2: error: ld returned 1 exit status
handeye_calib_camodocal/CMakeFiles/handeye_calib_camodocal.dir/build.make:215: recipe for target '/home/student/catkin_ws/devel/lib/handeye_calib_camodocal/handeye_calib_camodocal' failed
make[2]: *** [/home/student/catkin_ws/devel/lib/handeye_calib_camodocal/handeye_calib_camodocal] Error 1
CMakeFiles/Makefile2:2359: recipe for target 'handeye_calib_camodocal/CMakeFiles/handeye_calib_camodocal.dir/all' failed
make[1]: *** [handeye_calib_camodocal/CMakeFiles/handeye_calib_camodocal.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by schuhschuh** [comment]
Hi @1gen100!

I am not familiar with the library you want to build, which depends on gflags. The linker error suggests, however, that the build configuration of that library may need a fix. What happens is that "gflags_static", which is a CMake build target name, is not correctly resolved and replaced by the actual path of the corresponding static library (named "gflags.a" on Unix and "gflags.lib" on Windows).

You should be able to fix this by making sure that
a) find_package(gflags) is present in your project, best before target_link_libraries(beginner_... gflags_static)
b) Check that target "gflags_static" is defined using CMake code such as

```
if(TARGET gflags_static)
  message("Static gflags library target is defined")
else()
  message(FATAL_ERROR "Static gflags library is not defined")
endif()
```

One possibility that this library is not defined is if your project does not explicitly request a static library and your installation of gflags only contains a shared library, but not a static library. In this case, you may either require a static library, or use the build target "gflags" instead of "gflags_static" in the "target_link_libraries" call.

If this doesn't help, I suggest you contact the developers/maintainers of the software you try to build.

**Comment by 1gen100** [comment]
Thanks for the fast respons. 
a) every thing is in order foir this, here is some of the code:

find_package(Gflags REQUIRED)
find_package(Glog REQUIRED)
....
target_link_libraries(handeye_calib_camodocal
  ${catkin_LIBRARIES} ${GLOG_LIBRARIES}  ${GLOG_LIB}  ${GLOG_LIBS} ${OpenCV_LIBRARIES} ${CERES_LIBRARIES}
)

b) this part hasn't been done but it's because we only want the shared lib.

How do I get the statitc library? I only know how to get the shared one.

**Comment by schuhschuh** [comment]
- Where do you have the `FindGflags.cmake` module from that you seem to be using?
- How have you installed the gflags library? From source code or using binary package?
- What operating system are you on?

**Comment by 1gen100** [comment]
I'm using this github program:
https://github.com/jhu-lcsr/handeye_calib_camodocal

The `FindGflags.cmake` is in a cmake folder in my `/home/student/catkin_ws/src/handeye_calib_camodocal`.

You can see the code of the .cmake file here:
https://github.com/jhu-lcsr/handeye_calib_camodocal/blob/master/cmake/FindGflags.cmake

I have installed and downloaded the gflags library using the instruction:
https://github.com/gflags/gflags/blob/master/INSTALL.md

I'm using:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Comment by schuhschuh** [comment]
When you installed gflags via `apt-get` and are using this custom `FindGflags` module, you may not have the imported CMake build targets that are exported to `gflags-config.cmake` file. In this case, you will have to either fix the FindGflags module to define these imported targets using `add_library(gflags_static STATIC IMPORTED)` and by setting the appropriate `IMPORTED_*` target properties accordingly, or do so in your own project.

None of these issues can or need to be addressed by the gflags project, as the error is caused downstream.

**Comment by schuhschuh** [comment]
PS: You would no longer encounter this issue on Ubuntu 18.04... as the `libgflags-dev` package for bionic includes the `gflags-config.cmake` file that defines the import targets that you require.

See https://packages.ubuntu.com/bionic/amd64/libgflags-dev/filelist.

**Comment by 1gen100** [comment]
In my ignores i used both the first and the second one.
so I have a folder called "gflags".

I'm using ROS Kinetic for this project and they only support "ROS Kinetic ONLY supports Wily (Ubuntu 15.10), Xenial (Ubuntu 16.04) and Jessie (Debian 8) for debian packages."
but thank you for your help, I will try to see if i can get it working.

**Comment by 1gen100** [comment]
Thx for the help it could be the problem isn't the gflags, know i got a another error.
