### ISSUE TITLE
Failing to execute pytest or other binary commands

### ISSUE THREAD

**Issue by girishsv1986** [gflags/gflags#282]
Hi there,

I'm using gflags for accepting command line arguments in one of the script recently added in application. There are unit testcases in the application that I execute using pytest library. Unit test execution was working fine till the time GFLAGS library was not sys path. After adding gflags, the command line arguments provided to pytest or py.test or any other command in interpreted/interrupted by the GFlags and it ultimately throw back the following error.

> python_gflags-2.0-py2.6.egg/gflags.py:1319: in __call__
>     raise UnrecognizedFlagError(opt, value)
> E   UnrecognizedFlagError: Unknown command line flag 'cov-config'
> 
> ---------- coverage: platform linux2, python 2.7.5-final-0 -----------

Command I'm executing is mentioned below. Is there any way to disable/force fglags to ignore such commands?
`py.test --cov-config .coveragerc --cov-report html --cov=.`

**Comment by schuhschuh** [comment]
Hi, please submit your issue to [google/python-gflags](https://github.com/google/python-gflags). This repository contains the C++ library.

**Comment by girishsv1986** [comment]
Thanks, didn't noticed it's not a python flags repository.
