### ISSUE TITLE
Undefined symbols FlagRegister - cmake - fail to link gflags - Boost conflict

### ISSUE THREAD

**Issue by tgy** [gflags/gflags#291]
I have a problem in one of my projects where the program fails to compile because a linking error is raised on some gflags templated functions:
```
[100%] Linking CXX executable reproduce-issue
Undefined symbols for architecture x86_64:
  "google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, b
ool*, bool*)", referenced from:
      ___cxx_global_var_init.3 in reproduce.cpp.o
  "google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, in
t*, int*)", referenced from:
      ___cxx_global_var_init in reproduce.cpp.o
ld: symbol(s) not found for architecture x86_64
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [reproduce-issue] Error 1
make[2]: *** [CMakeFiles/reproduce-issue.dir/all] Error 2
make[1]: *** [CMakeFiles/reproduce-issue.dir/rule] Error 2
make: *** [reproduce-issue] Error 2
```
I have managed to reproduce this issue with a small example. Here are the `CMakeLists.txt` and `reproduce.cpp` files:
```cmake
cmake_minimum_required(VERSION 3.6 FATAL_ERROR)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++1z -Wall -W -pedantic -g")
set(CMAKE_CXX_FLAGS_DEBUG
    "${CMAKE_CXX_FLAGS} -std=c++1z -Wall -W -pedantic -g")
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED on)

project(reproduce LANGUAGES CXX)

add_subdirectory(gflags)

find_package(Boost 1.62.0 REQUIRED)
include_directories(${Boost_INCLUDE_DIRS})

add_executable(
  reproduce-issue
  reproduce.cpp
)
target_link_libraries(reproduce-issue gflags)
```

```cpp
#include <gflags/gflags.h>

DEFINE_int32(j, -1, "nb of jobs");
DEFINE_bool(skip, false, "whether to skip already done computations");

int main(void)
{
  return 0;
}
```

Note that the last version of gflags is cloned next to these two files.

Note also that if I move the `add_subdirectory(gflags)` instruction after `include_directories(${Boost_INCLUDE_DIRS})` everything works fine.

**Comment by schuhschuh** [comment]
A few more details about which OS, compiler + version, and Boost library you are using may be needed. I tried your `reproduce` example on macOS 10.14.6 with clang 11.0.0 and Boost 1.70 (installed with Homebrew) and it compiled without any error.

**Comment by tgy** [comment]
```bash
$ echo $CXX
/usr/local/Cellar/llvm/8.0.1/bin/clang++
$ grep BOOST_LIB_VERSION `locate 'boost/version.hpp'`
//  BOOST_LIB_VERSION must be defined to be the same as BOOST_VERSION
#define BOOST_LIB_VERSION "1_70"
viovene@223-239 ~/p/phd/mdnotes (master)
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G87
```

**Comment by aimi19930326** [comment]
how to solve this problem?  I meet this problem too.

**Comment by tgy** [comment]
@aimi19930326 i think i solved it at the time by moving `add_subdirectory(gflags)` after the `find_package(Boost 1.62.0 REQUIRED)` but i'm not sure. you could try that

**Comment by schuhschuh** [comment]
I tried and noticed a mismatch between the namespace of the symbols in the static library (`gflags`), and the undefined reference error message (`google`).

A workaround is to `set(GFLAGS_NAMESPACE "google")` before `add_subdirectory(gflags)`.

**Comment by schuhschuh** [comment]
At [this line of gflags/CMakelists.txt](https://github.com/gflags/gflags/blob/ef8e134d48af81f45f1fffe095ff157c5785e4a8/CMakeLists.txt#L154), the default value differs when you built gflags as standalone library or as subproject. In the latter case, the default is `"gflags"`. I am not clear yet how `include_directories(${Boost_INCLUDE_DIRS})` affects the namespace definition. It should be a C macro definition in header [gflags/gflags_declare.h](https://github.com/gflags/gflags/blob/ef8e134d48af81f45f1fffe095ff157c5785e4a8/src/gflags_declare.h.in#L43), which is included by `gflags/gflags.h`.

Could `Boost_INCLUDE_DIRS` contain a path that contains a system-wide installation of the gflags library? One that uses the "google" namespace rather and sets it in the header? That would explain.

**Comment by schuhschuh** [comment]
A better solution is to fix the include path order:
```
add_subdirectory(gflags)
get_target_property(gflags_include_dirs gflags INTERFACE_INCLUDE_DIRECTORIES)
include_directories(BEFORE "${gflags_include_dirs}")
```

And even better, don't use `include_directories()` at all. Use CMake target properties.
