### ISSUE TITLE
How to reload a flagfile

### ISSUE THREAD

**Issue by MaggieCui** [gflags/gflags#296]
can SetCommandLineOption("flagfile", $flagfilepath)  re-parse all flags in flagfile?

**Comment by schuhschuh** [comment]
I think you may be interested in ParseCommandLineNonHelpFlags or ReparseCommandLineNonHelpFlags. As these internally call [ProcessFlagfileLocked](https://github.com/gflags/gflags/blob/d9b184bd0026b16bb4c2fded75d56fb2cce50d66/src/gflags.cc#L1947) with `set_mode=SET_FLAGS_VALUE`, this will [override flag values](https://github.com/gflags/gflags/blob/d9b184bd0026b16bb4c2fded75d56fb2cce50d66/src/gflags.cc#L862) even if they have been set before.
