### ISSUE TITLE
gflags does not work on Windows without msys

### ISSUE THREAD

**Issue by tomlu** [gflags/gflags#303]
There are a couple on genrules invoking awk around here: https://github.com/gflags/gflags/blob/master/bazel/gflags.bzl#L4

genrules do not work on Windows without msys installed, which is an undesirable dependency. In this case they also use awk

I am happy to address this with a pull request. A few options comes to mind:

* Add a simple cc_binary and a simple starlark rule to do the processing required instead of using awk through a genrule. I tried this locally. It adds about 150 lines to the depot (one cc file and one bzl file for the custom rule), but no new dependencies.

* Pull in awk from GitHub via an external WORKSPACE dependency and replace genrules with a custom awk starlark rule. Obviously this adds a dependency.

* Build awk for windows only and check in a binary, then use select to pick between genrules or custom awk. I'm not personally a fan of checking in binaries, but it's an option.

**Comment by tomlu** [comment]
Ping on this. I'm happy to do all the legwork. I am @tomlu internally at Google if you need to speak to me directly.

**Comment by schuhschuh** [comment]
@tomlu Thanks for looking into this and offering your help. I would appreciate it as I'm myself not a user of Bazel. Does the second option only relate to introducing a dependency for Bazel build, but CMake users will be unaffected by this? What is your preference between options 1 and 2?

Myself, I prefer if this change is isolated to Bazel users. For Bazel users, I think this tool was intended to deal with numerous inter-project dependencies, in which case adding a dependency for the build process may not be this harmful, also considering the caching that's done.

**Comment by tomlu** [comment]
> Does the second option only relate to introducing a dependency for Bazel build, but CMake users will be unaffected by this?

Yes, that would be the case, both for 1) and 2). This all happens in `WORKSPACE` and `BUILD` files.

> What is your preference between options 1 and 2?

I did 1) internally. It might be the easier, more self-contained fix. Like I said it's about 150 lines of a fairly trivial .cc binary. If you don't expect the awk command to change very often, or require more complicated things, it's probably what I'd do.

**Comment by schuhschuh** [comment]
Alright, I don't mind having this extra file in the `bazel/` folder.
