### ISSUE TITLE
build with bazel

### ISSUE THREAD

**Issue by liukr001** [gflags/gflags#309]
Using the bazel compiler, how to configure the workspace; the following configuration will report an error:
git_repository(
     name ="com_github_gflags_gflags",
     remote ="https://github.com/gflags/gflags.git",
     tags ="v2.2.2",
)

ERROR: /home/guitar/ws/google_bazel_ws/mytest4_gflag/WORKSPACE:3:15: //external:com_github_gflags_gflags: expected value of type'list(string)' for attribute'tags' in'git_repository' rule, but got "v2 .2.2" (string)
ERROR: error loading package'external': Package'external' contains errors
INFO: Elapsed time: 0.109s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by panzhongxian** [comment]
I have fixed this in #317 . Could you help to update the static page in <http://gflags.github.io/gflags/> ?

**Comment by schuhschuh** [comment]
Thanks for the reminder, forgot the gh-pages branch now needs to be update explicitly. Done (cf. https://github.com/gflags/gflags/commit/519ca1bfa4d9a59b8f0c18c0b3ce671cfec12c8e#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051).
