### ISSUE TITLE
string flag length is incorrect if it's longer than the default value

### ISSUE THREAD

**Issue by sillykelvin** [gflags/gflags#312]
Assume we have the following code:

```
#include "gflags/gflags.h"

DEFINE_string(str, "12345", "test");

int main(int argc, char** argv) {
    google::ParseCommandLineFlags(&argc, &argv, true);

    std::string str = FLAGS_str;
    printf("%s(%lu)\n", FLAGS_str.c_str(), FLAGS_str.length());
    printf("%s(%lu)\n", str.c_str(), str.length());

    return 0;
}
```

Then run it with different `str` flag:

```
$ ./a.out -str='12'
12(4)
12(4)
$ ./a.out -str='123456789'
123456789(4)
1234(4)
```

As you can see, the length of `FLAGS_str` is always 4(but `c_str()` function returns the correct string), this leads to string truncation when assigned to a `std::string` and its value is longer than 4.

I am runing the code on Debina-9 64bit with gflags v2.1.2, I don't know if it's intended or it's just a bug?

Thanks,
Kelvin

**Comment by schuhschuh** [comment]
Thanks for reporting this. I was however not able to reproduce the issue:

```
> bin/gflags_issue_312 -str="1234567"
1234567(7)
1234567(7)
> bin/gflags_issue_312 -str="123456789"
123456789(9)
123456789(9)
```

**Comment by sillykelvin** [comment]
Thanks for your response.

Finally it turns out to be a compiler compatibility issue: gflags is compiled with GCC 4.x, and the program is compiled with GCC 6.x, according to [this](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html), **GCC 5.x introduced a new ABI for `std::string` which is not compatible with the former one, and it's enabled by default**.

To those who have the same issue: the new incompatible ABI can be disabled with definition `-D_GLIBCXX_USE_CXX11_ABI=0`, and if you use cmake, just add the following snippet:

```
if (CMAKE_COMPILER_IS_GNUCXX)
    if (CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 5.0)
        add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)
    endif()
endif()
```

**Comment by schuhschuh** [comment]
Thanks for digging deeper into the cause and sharing your findings here!
