### ISSUE TITLE
Remove self-referencing sub-module

### ISSUE THREAD

**Issue by infn-ke** [gflags/gflags#314]
The doc folder is a sub-module self-referencing the parent repo. Can we remove that and simply check in the doc folder instead?

It may work with Linux git, but causes issues with some tools, e.g. bitbake dead-locks, see ticket:

https://bugzilla.yoctoproject.org/show_bug.cgi?id=14045

**Comment by schuhschuh** [comment]
Thanks for bringing this to my attention. Wouldn't it rather seem to be a limitation of bitbake that would need to be fixed?

The reason for the submodule reference is to not have a duplicate `gh-pages` branch required to publish the documentation on GitHub. An alternative may be use of `git subtree` to keep the `doc/` folder in sync with this `gh-pages` branch, but the use of a submodule made this dependency more explicit.
