### ISSUE TITLE
Using command line form "-something false" doesn't work for a bool flag

### ISSUE THREAD

**Issue by schuhschuh** [gflags/gflags#32]
Original [issue 21](https://code.google.com/p/gflags/issues/detail?id=21) created by schuhschuh on 2008-09-09T14:18:36.000Z:

<b>What steps will reproduce the problem?</b>
# include &lt;stdio.h&gt;
# include &lt;google/gflags.h&gt;

DEFINE_bool (something, true, &quot;Set this for something.&quot;);

int main(int argc, char **argv)
{
 google::ParseCommandLineFlags(&amp;argc, &amp;argv, true);

 fprintf(stderr, &quot;FLAGS_something = %d\n&quot;, FLAGS_something);
 return 0;
}

<b>What is the expected output? What do you see instead?</b>

According to the how-to, the following:

test_prog --nosomething
test_prog --something=false
test_prog --something false
test_prog -nosomething
test_prog -something=false
test_prog -something false

should all set the something flag to false.  The ones with a space
between the flag and the argument to the flag do not work.  Spaces
work for the other types (at least double and string) but not bool.  I
realize that the preferred syntax is --something/--nosomething but the
docs say that the spaces are OK.

<b>What version of the product are you using? On what operating system?</b>

The rc1 download and the SVN version both have the same problem.

<b>Please provide any additional information below.</b>

**Comment by arjology** [comment]
> Comment [#1](https://code.google.com/p/gflags/issues/detail?id=21#c1) originally posted by schuhschuh on 2008-09-10T18:52:22.000Z:
> 
> You are absolutely right -- we don't support "--flag value" for boolean flags. I
> have updated the documentation to reflect this. It will be in the next release.

Any update on supporting `--flag value` ?

**Comment by schuhschuh** [comment]
See also #311 for reasons to not support `--bool_flag <value>` syntax.
