### ISSUE TITLE
modify a parameter in flagfile, then read it, when the program is running, how can i realize it?

### ISSUE THREAD

**Issue by jcyhcs** [gflags/gflags#331]
hi,professor:
i use gflags as config files tools, i need a function, it is:  i have a parameter in flagfile, my program running, process will get this parameter all the time, of course, my process can't stop. so i need modify the parameter in flagfile, then it feedback to my running program, 
how can i realize it ? 
please help me!

**Comment by zdanek** [comment]
@jcyhcs you need a separate thread that polls file timestamp and/or parses flags
If a change occurs you can reload data. 
Informing all program parts that a config has changed is another challenge. Not very complicated but it should be taken into an account:

1) do nothing - just update params and wait until program will need them
2) use some kind of events/listeners to inform every "configured" module/program part that a config has changed

**Comment by schuhschuh** [comment]
Closing as answered / inactive. Feel free to reopen if still interested in a more concrete answer.
