### ISSUE TITLE
Support uint32 as flag type

### ISSUE THREAD

**Issue by schuhschuh** [gflags/gflags#99]
Original [issue 88](https://code.google.com/p/gflags/issues/detail?id=88) created by schuhschuh on 2014-10-17T22:58:05.000Z:

The current supported types include int32, int64, and uint64. We have a flag (a seed to a random number generator) which is a uint32.

We currently use int64, then explicitly cast. This is perfectly good workaround, but it seems nicer if it were just supported directly.

**Comment by schuhschuh** [comment]
Given that there is an unsigned flag type for 64-bit integers, it is probably reasonable to request/expect the same for 32-bit integers.

**Comment by bazineta** [comment]
We've done this on our local copy and it was very straightforward.  Let me know if you'd like a PR.

**Comment by schuhschuh** [comment]
@bazineta A PR would be very welcome. I image it's not much of a change, though.

**Comment by bazineta** [comment]
Indeed not much of a change.  Just ones and zeros, the only trick is to get them in the right order.  PR #147

**Comment by bazineta** [comment]
And the right order...is sometimes difficult.  Reviewing the PR, I see the following error:

FV_MAX_INDEX = 7

Sigh..the tests passed...I think that's the only issue.

**Comment by schuhschuh** [comment]
I think this mistake could be avoided by not assigning enumerated values explicitly and using ```FV_NUM_TYPES``` instead of max index. But that's another change... adding uint32 seemed to have needed more copy-paste-edit changes I thought. Thanks for the PR!
